"""The client's two mirrors cannot rot without this file going red.

`frontend/tests/fixtures/builderBackEdges.json`, `builderProblemCodes.json` and
`models.json` are generated by `scripts/emit_builder_fixtures.py` from the real
`bounds.back_edge_indices`, the real `compiler.document_problems` and the real
`registry_document`. The TypeScript suite reads them and holds
`builderGraph.ts::backEdges`, `types/builder.ts::PROBLEM_CODES` and
`data/models.ts` to what they say.

The third arrived with plan 05, and it is the one where the byte-compare buys
the most: the roster is DATA rather than a derived answer, so a client mirror of
it has nothing to disagree with except the file, and a stale copy would price a
graph in the meter at yesterday's numbers while the server refused it at
today's. It is emitted through the SAME `registry_document` that
`GET /api/builder/models` serves, so the fixture cannot describe a row
differently from the route it stands for.

That arrangement has one hole, and it is the hole that matters: the fixtures are
FILES. Move a bound, add a problem code, change a message, and the Python
suite stays green, the frontend suite stays green against the stale copy, and
the canvas quietly starts drawing the wrong edge dashed or dropping a problem it
has never heard of. Spec ruling R7 admits the back-edge mirror on exactly this
condition - that CI regenerates and compares - and it is the only mechanism in
the whole plan that survives a contributor who has not read the spec.

So this test regenerates both fixtures in memory and byte-compares them against
what is committed. It is the sibling of
`test_problem_code_declarations.py`, which guards the same mirror from the other
end: that file asserts every problem code is written in the SHAPE the frontend's
grep can find, this one asserts the generated fixtures are CURRENT. Neither
subsumes the other - a code declared in the right shape can still be absent from
a stale fixture, and a fixture regenerated today can still hide a code written
as a literal.

**Line endings.** `core.autocrlf` is `true` in this repository, so the working
tree holds CRLF and the object store holds LF. A raw byte comparison would
therefore fail on every Windows checkout and pass on every Linux one - a gate
that reports the platform instead of the drift. `committed()` normalises before
comparing, which keeps the comparison about content while staying exact about
it.

No cost: this reads `brief_crew.builder` and two JSON files. No network, no
model, no credential.
"""

from __future__ import annotations

import json
import pathlib
import sys
import unittest

REPO = pathlib.Path(__file__).resolve().parents[2]
if str(REPO) not in sys.path:  # pragma: no cover - import bootstrap
    sys.path.insert(0, str(REPO))

from scripts.emit_builder_fixtures import (  # noqa: E402
    BACK_EDGES_PATH,
    COMPILED_PREVIEW_PATH,
    MODELS_PATH,
    PREVIEW_CREDENTIAL_ID,
    PREVIEW_CREDENTIAL_LABEL,
    PROBLEM_CODES_PATH,
    PROBLEM_SCENARIOS,
    TEMPLATE_DOCUMENTS_PATH,
    build_back_edges,
    build_compiled_preview,
    build_models,
    build_problem_codes,
    build_templates,
    committed,
    render,
    template_documents,
)

REGENERATE = "./.venv/Scripts/python.exe scripts/emit_builder_fixtures.py"
#: Spelled out so the two regeneration commands render on their own lines
#: in a failure message. A test that says how to fix itself is the only
#: reason a generated fixture is safe to commit.
NEWLINE = chr(10)


class BackEdgeFixtureTests(unittest.TestCase):
    """`builderBackEdges.json` still says what `back_edge_indices` says."""

    def test_the_committed_fixture_is_what_the_generator_produces_now(self) -> None:
        self.assertEqual(
            committed(BACK_EDGES_PATH),
            render(build_back_edges()),
            "frontend/tests/fixtures/builderBackEdges.json is stale, so the "
            "TypeScript back-edge mirror is being checked against an answer this "
            "build no longer gives. Regenerate with:\n    " + REGENERATE,
        )

    def test_every_case_is_permuted_and_the_permutations_disagree(self) -> None:
        """A fixture whose answer is order-invariant would prove nothing.

        The mirror returns POSITIONS in `document.edges`, and the whole reason
        R7 asks for order-permuted documents is that two parallel edges between
        one pair are equal as values - only the position tells them apart. If
        every ordering of some case gave the same answer, that case would pass
        against a mirror that ignored order entirely.
        """

        payload = json.loads(BACK_EDGES_PATH.read_text(encoding="utf-8"))
        cases = payload["cases"]
        self.assertGreaterEqual(len(cases), 5, "too few topologies to be a gate")

        for case in cases:
            with self.subTest(case=case["name"]):
                permutations = case["permutations"]
                edge_count = len(case["document"]["edges"])
                self.assertEqual(
                    len(permutations[0]["order"]),
                    edge_count,
                    "an order must name every edge exactly once",
                )
                for row in permutations:
                    self.assertEqual(
                        sorted(row["order"]),
                        list(range(edge_count)),
                        "an order must be a permutation, not a subset",
                    )

        answers = {
            tuple(row["back_edge_indices"])
            for case in cases
            for row in case["permutations"]
        }
        self.assertGreater(
            len(answers),
            1,
            "every permutation in every case returned the same positions, so this "
            "fixture would be satisfied by a mirror that ignored edge order",
        )

    def test_at_least_one_case_closes_nothing_and_one_closes_two(self) -> None:
        """Both ends of the answer, so neither a stub nor a false positive passes."""

        payload = json.loads(BACK_EDGES_PATH.read_text(encoding="utf-8"))
        widths = {
            len(row["back_edge_indices"])
            for case in payload["cases"]
            for row in case["permutations"]
        }
        self.assertIn(0, widths, "no acyclic case: a mirror returning [] would pass")
        self.assertIn(
            2, widths, "no two-loop case: the cycle ceiling is 3 and nothing exercises it"
        )


class ProblemCodeFixtureTests(unittest.TestCase):
    """`builderProblemCodes.json` still carries one live instance of every code."""

    def test_the_committed_fixture_is_what_the_generator_produces_now(self) -> None:
        self.assertEqual(
            committed(PROBLEM_CODES_PATH),
            render(build_problem_codes()),
            "frontend/tests/fixtures/builderProblemCodes.json is stale. Either a "
            "problem code was added, removed or renamed, or a message the canvas "
            "renders VERBATIM has changed. Regenerate with:\n    " + REGENERATE,
        )

    def test_every_declared_code_has_an_instance(self) -> None:
        """The completeness claim, asserted against the file rather than the run.

        `build_problem_codes` already refuses to emit an incomplete fixture, so
        this cannot fail while the byte-compare above passes - which is the
        point. It is here so a reader of the committed FILE can see the property
        stated, and so a future emitter that grows a `--partial` escape hatch
        breaks a test rather than a guarantee.
        """

        from scripts.emit_builder_fixtures import _declared_codes

        payload = json.loads(PROBLEM_CODES_PATH.read_text(encoding="utf-8"))
        self.assertEqual(
            sorted(_declared_codes()),
            payload["codes"],
            "the fixture's code list and the declaring modules disagree",
        )
        self.assertEqual(
            payload["codes"],
            sorted(instance["code"] for instance in payload["instances"]),
            "the code list and the instances disagree",
        )

    def test_every_instance_carries_the_document_it_was_found_in(self) -> None:
        """An anchor is only useful if the node it names is somewhere to be had.

        `problemsByNode` is an index, and a client test that builds one from a
        problem whose `node_id` matches no node in any document it also holds is
        asserting about an index nobody could construct.
        """

        payload = json.loads(PROBLEM_CODES_PATH.read_text(encoding="utf-8"))
        documents = payload["documents"]
        for instance in payload["instances"]:
            with self.subTest(code=instance["code"]):
                self.assertIn(instance["scenario"], documents)
                anchor = instance["problem"]["node_id"]
                if anchor is None:
                    continue
                ids = {node["id"] for node in documents[instance["scenario"]]["nodes"]}
                self.assertIn(
                    anchor,
                    ids,
                    "a problem anchors to a node its own document does not contain",
                )

    def test_no_scenario_claims_a_code_twice(self) -> None:
        """One instance per code, so a client test cannot pick the convenient one."""

        claimed: list[str] = []
        for scenario in PROBLEM_SCENARIOS:
            claimed += scenario["expects"]
        duplicates = sorted({code for code in claimed if claimed.count(code) > 1})
        self.assertEqual(duplicates, [], "two scenarios claim the same code")

    def test_the_messages_are_whole_sentences_with_their_anchors(self) -> None:
        """The two properties the canvas depends on and neither type checks.

        A message is rendered verbatim into `ProblemsPanel` and a hover panel, so
        an empty or truncated one is a blank row. An anchor is what `fitView`
        centres on, so a code that carries neither must be a DOCUMENT-level
        problem - it lands in its own group at the top of the panel and is
        deliberately not anchored anywhere.
        """

        payload = json.loads(PROBLEM_CODES_PATH.read_text(encoding="utf-8"))
        document_level: list[str] = []
        for instance in payload["instances"]:
            problem = instance["problem"]
            with self.subTest(code=problem["code"]):
                self.assertIn(problem["severity"], ("error", "warning"))
                self.assertGreater(
                    len(problem["message"]),
                    30,
                    "a problem message is the whole of what the author is told",
                )
                if problem["node_id"] is None and problem["edge_id"] is None:
                    document_level.append(problem["code"])

        # Named rather than merely counted: each of these is a fact about the
        # graph as a whole, and the canvas has a group for exactly that. A code
        # arriving here unexpectedly is a problem that would have been rendered
        # nowhere until `ProblemsPanel`'s document group was written.
        self.assertEqual(
            sorted(document_level),
            [
                "billable-count",
                "budget-over-ceiling",
                "budget-unpriced-model",
                "ident-collision",
                "input-field-undeclared",
                "join-unknown-node",
                "no-input-node",
                "no-output-node",
                "node-count",
                # 09 D6's two. They carry `field` - the state key - rather than
                # a node or an edge, because a declared state key is a fact
                # about the DOCUMENT and there is no node on the canvas to rim.
                "state-key-reserved",
                "state-schema-invalid",
            ],
            "the set of problems carrying NO anchor moved; ProblemsPanel's "
            "document-level group is the only surface that renders these",
        )


class ModelFixtureTests(unittest.TestCase):
    """`models.json` still says what `data/models.json` says - criterion 9."""

    def test_the_committed_fixture_is_what_the_generator_produces_now(self) -> None:
        self.assertEqual(
            committed(MODELS_PATH),
            render(build_models()),
            "frontend/tests/fixtures/models.json is stale, so the client's model "
            "mirror is being checked against a roster this build no longer serves. "
            "Regenerate with:\n    " + REGENERATE,
        )

    def test_it_is_the_registry_row_for_row(self) -> None:
        """Read from `config.MODEL_REGISTRY` rather than from the generator.

        The byte-compare above proves the fixture matches what the generator
        emits TODAY; this proves what the generator emits is the registry, so a
        generator that started dropping a field would fail here rather than
        being ratified by its own output.
        """

        from brief_crew.config import MODEL_REGISTRY

        payload = json.loads(MODELS_PATH.read_text(encoding="utf-8"))
        self.assertEqual(
            [row["id"] for row in payload["models"]],
            [model.id for model in MODEL_REGISTRY],
        )
        for row, model in zip(payload["models"], MODEL_REGISTRY):
            with self.subTest(model=model.id):
                self.assertEqual(row["cost_in"], model.cost_in)
                self.assertEqual(row["cost_out"], model.cost_out)
                self.assertEqual(
                    row["cost_in_max_endpoint"], model.cost_in_max_endpoint
                )
                self.assertEqual(row["supports_tools"], model.supports_tools)
                self.assertEqual(row["supports_json_mode"], model.supports_json_mode)
                self.assertEqual(row["supports_reasoning"], model.supports_reasoning)
                self.assertEqual(row["supports_vision"], model.supports_vision)

    def test_it_carries_the_capability_disagreements_the_picker_renders(self) -> None:
        """A fixture where every flag is true would gate nothing, and prove less.

        The client's disabled-with-tooltip state only has something to render
        when some row lacks something. Measured 2026-09-04: `gpt-4.1-nano` and
        `gpt-4o-mini` publish no reasoning at all, and three rows take no image
        input. If a future roster is uniform, this fails and says so rather than
        letting the gating tests pass over a fixture that cannot exercise them.
        """

        payload = json.loads(MODELS_PATH.read_text(encoding="utf-8"))
        rows = payload["models"]
        self.assertTrue(
            any(not row["supports_reasoning"] for row in rows),
            "no row lacks reasoning, so the reasoning gate renders nowhere",
        )
        self.assertTrue(
            any(not row["supports_vision"] for row in rows),
            "no row lacks vision, so the vision badge is a constant",
        )


if __name__ == "__main__":
    unittest.main()


class TemplateFixtureTests(unittest.TestCase):
    """Plan 14 criterion 3: every gallery template's recorded answer is current.

    The other three fixtures in this file are DERIVED from Python and compared
    against themselves. A template is not: the document is authored in
    TypeScript, `scripts/dump-templates.mjs` carries it across, and what is
    regenerated and compared here is the ANSWER - the validation, the price and
    the served vocabulary - over the document that file holds.

    So the bridge is gated at both ends and neither end can stand in for the
    other. Edit a template and forget the dump, and
    `frontend/tests/templates.spec.ts` goes red because the TypeScript no longer
    equals `documents.json`. Run the dump and forget this generator, and this
    goes red because the recorded answer no longer matches the document it is
    offered as proof of. Move a bound, a price or a problem message, and this
    goes red on its own.
    """

    def test_every_committed_template_fixture_is_current(self) -> None:
        for path, content in build_templates():
            with self.subTest(fixture=path.name):
                self.assertEqual(
                    committed(path),
                    content,
                    f"frontend/tests/fixtures/templates/{path.name} is stale: the "
                    "template's document, this build's bounds, its prices or a "
                    "problem message has moved. Regenerate with:" + NEWLINE
                    + "    node scripts/dump-templates.mjs" + NEWLINE
                    + "    " + REGENERATE,
                )

    def test_the_dump_covers_every_template_the_gallery_renders(self) -> None:
        dumped = template_documents()
        self.assertEqual(
            sorted(dumped["documents"]),
            sorted(list(dumped["order"]) + list(dumped["more"])),
            f"{TEMPLATE_DOCUMENTS_PATH.name} lists a row it has no document for",
        )
        self.assertEqual(
            sorted(dumped["cards"]),
            sorted(dumped["documents"]),
            "a template with no card, or a card with no template",
        )

    def test_every_fixture_records_a_clean_answer(self) -> None:
        """Stated against the FILE, so a reader of the committed fixture sees it.

        `test_templates.py` asserts the same property against a freshly computed
        answer. Both are here because they fail for different reasons: that one
        catches a template that stopped validating, this one catches a fixture
        that was regenerated from a stale dump and recorded a clean answer for a
        document nobody ships.
        """

        for path, content in build_templates():
            with self.subTest(fixture=path.name):
                payload = json.loads(content.decode("utf-8"))
                self.assertTrue(payload["validation"]["valid"])
                self.assertEqual(payload["validation"]["problems"], [])
                budget = payload["validation"]["budget"]
                self.assertEqual(budget["unpriced_models"], [])
                self.assertFalse(budget["over_ceiling"])


class CompiledPreviewFixtureTests(unittest.TestCase):
    """`builderCompiledPreview.json` still says what `render_preview` says.

    Plan 13 criterion 5. The Code tab renders `yaml` and `python` VERBATIM - it
    generates neither - so what a TypeScript test can usefully assert is that
    the strings it renders are the strings this build produces. A hand-written
    fixture would drift the first time `_render_python` changed a line, and the
    tab's test would go on passing over a rendering nobody ships.
    """

    def test_the_committed_fixture_is_what_the_generator_produces_now(self) -> None:
        self.assertEqual(
            committed(COMPILED_PREVIEW_PATH),
            render(build_compiled_preview()),
            "frontend/tests/fixtures/builderCompiledPreview.json is stale, so "
            "the Code tab is being checked against a rendering this build no "
            "longer produces. Regenerate with:" + NEWLINE + "    " + REGENERATE,
        )

    def test_the_python_rendering_labels_the_credential_and_never_names_a_key(
        self,
    ) -> None:
        """The one substitution in the whole preview, pinned from this end too.

        `test_preview.py` proves the renderer cannot read a key, against a real
        vault with a real sentinel. This proves the FIXTURE carries the shape
        that proof is about - a fixture whose graph named no credential would
        leave the tab's only security-relevant assertion vacuous, and would do
        it silently.
        """

        payload = json.loads(COMPILED_PREVIEW_PATH.read_text(encoding="utf-8"))
        self.assertIn(f"<credential: {PREVIEW_CREDENTIAL_LABEL}>", payload["python"])
        # The YAML is the literal declaration and carries the ID, which is the
        # asymmetry `builder_api.py` documents: the reference is what runs, the
        # label is what a person reads.
        self.assertIn(PREVIEW_CREDENTIAL_ID, payload["yaml"])
        self.assertNotIn(PREVIEW_CREDENTIAL_ID, payload["python"])

    def test_the_timestamp_is_pinned_rather_than_normalised_away(self) -> None:
        """A generated_at from `now()` would make this fixture unpinnable.

        `render_preview` takes it as a parameter for exactly this reason, and
        stripping the field instead would be a field the byte-compare stopped
        checking.
        """

        payload = json.loads(COMPILED_PREVIEW_PATH.read_text(encoding="utf-8"))
        self.assertEqual(payload["generated_at"], "2026-01-01T00:00:00+00:00")
