import type { FrameData, FrameKind, FrameLevel, GateDerivedField } from '../types/studio'

export interface MockScriptStep {
  delayMs: number
  frame: FrameData
}

/**
 * Node ids are `ValidatorFlow` method names, exactly as `MOCK_GRAPH` and the
 * live frame stream use them. Naming them once here keeps the script and the
 * graph from drifting apart again, and `mockGraph.spec.ts` fails if any of them
 * stops existing in the descriptor.
 */
const NODE = {
  scope: 'scope_idea',
  scopeGate: 'confirm_scope',
  scopeRouter: 'route_scope',
  market: 'research_market',
  sentiment: 'research_sentiment',
  feasibility: 'research_feasibility',
  synthesis: 'synthesize',
  verdictGate: 'review_verdict',
  verdictRouter: 'route_verdict',
  report: 'write_report',
  output: 'persist',
} as const

/**
 * The service builds gate prompts in `RunRegistry._gate_prompt`: a uuid5
 * `gate_id`, the Flow method name as `node_id`, `approve`/`revise` options, and
 * a payload split in two - `fields`, the values an operator edit actually
 * reaches, and `derived`, the values they may only read. The two prompts below
 * reproduce that split rather than a tidier invention, so the gate card is
 * rehearsed against the payload it will really receive.
 *
 * This is where the read-only split became visible in the first place: the
 * verdict prompt used to be nineteen editable inputs, four of which `Verdict`
 * recomputes and discards. It is now one note field and a read-only block, and
 * the block below is the real thing - generated by feeding a real `Verdict`
 * through `_split_gate_fields('review_verdict', ...)`:
 *
 *     _split_gate_fields('review_verdict', verdict.model_dump(mode='json'))
 */
const SCOPE_GATE_ID = '0f6a1c25-9a41-5c2e-8f0e-2b1d5f6a7c30'
const VERDICT_GATE_ID = '7c4b8e10-3d52-5a9f-b6c1-4e8a0d2f9b17'

/**
 * `ScopedIdea`, stringified the way the service stringifies it. Every field is
 * editable and nothing is derived: `route_scope` applies the edited object
 * verbatim, so revising the scope by hand is exactly what this gate is for.
 * `feedback` is the free-text lever both gates carry - on a Revise reply it
 * becomes the reviving crew's `human_override`.
 */
const SCOPE_FIELDS: Record<string, string> = {
  startup_idea: 'An AI tool that turns Figma files into production React',
  category: 'Design-to-code tooling',
  target_user: 'Frontend product teams shipping React from Figma handoffs',
  problem: 'Handoff-to-code rework consumes a sprint per redesign',
  technology_claim: 'Figma node trees can be compiled to typed, themed React components',
  market_query: 'figma to react code generation tools pricing',
  community_queries: '["figma handoff pain", "design to code tools worth it"]',
  tech_queries: '["figma-to-react", "design tokens codegen"]',
  assumptions: '["Teams re-implement designs by hand", "Component libraries are already in place", "Design files are reasonably structured"]',
  scoping_gaps: '["No evidence yet on enterprise design-system constraints"]',
  as_of: '2026-08-29',
  feedback: '',
}

/**
 * The verdict gate's editable half. One field, because every field of a
 * `Verdict` is either arithmetic the schema recomputes and discards or an
 * evidence-scored input the rubric guardrails bind - neither survives being
 * typed into. Disagreeing with a verdict means Revise plus a note, which sends
 * the Synthesist back to rescore against the same evidence.
 */
const VERDICT_FIELDS: Record<string, string> = { feedback: '' }

/**
 * The verdict gate's read-only half, in payload order. Generated from a real
 * `Verdict`, so the numbers are the ones the deterministic rubric actually
 * produces for those five dimension scores - composite 5.0, confidence 0.7,
 * band HIGH - rather than a plausible-looking invention the schema would
 * overwrite on sight.
 */
const VERDICT_DERIVED: GateDerivedField[] = [
  { key: "demand", kind: "json", value: "{\n  \"score\": 2,\n  \"anchor_matched\": \"Scattered complaints, no paid workaround\",\n  \"evidence_urls\": [\n    \"https://news.ycombinator.com/item?id=39218841\",\n    \"https://news.ycombinator.com/item?id=38997120\"\n  ],\n  \"evidence_thin\": true\n}" },
  { key: "market", kind: "json", value: "{\n  \"score\": 3,\n  \"anchor_matched\": \"Named segment with observable pricing\",\n  \"evidence_urls\": [\n    \"https://www.builder.io/pricing\",\n    \"https://locofy.ai/pricing\",\n    \"https://anima.app/pricing\"\n  ],\n  \"evidence_thin\": false\n}" },
  { key: "competitive_room", kind: "json", value: "{\n  \"score\": 2,\n  \"anchor_matched\": \"Several funded incumbents, no clear wedge\",\n  \"evidence_urls\": [\n    \"https://www.builder.io/\",\n    \"https://locofy.ai/\",\n    \"https://anima.app/\"\n  ],\n  \"evidence_thin\": false\n}" },
  { key: "feasibility", kind: "json", value: "{\n  \"score\": 4,\n  \"anchor_matched\": \"Open-source prior art covers the core path\",\n  \"evidence_urls\": [\n    \"https://github.com/dtinth/figma-to-react\",\n    \"https://github.com/plugins/figma-api\",\n    \"https://github.com/tokens-studio/figma-plugin\"\n  ],\n  \"evidence_thin\": false\n}" },
  { key: "headroom_over_free", kind: "json", value: "{\n  \"score\": 2,\n  \"anchor_matched\": \"Free tiers already cover the common case\",\n  \"evidence_urls\": [\n    \"https://www.builder.io/pricing\",\n    \"https://locofy.ai/pricing\"\n  ],\n  \"evidence_thin\": true\n}" },
  { key: "evidence_counts", kind: "json", value: "{\n  \"market\": 12,\n  \"sentiment\": 7,\n  \"feasibility\": 18\n}" },
  { key: "market_coverage", kind: "text", value: "0.83" },
  { key: "sentiment_coverage", kind: "text", value: "0.41" },
  { key: "feasibility_coverage", kind: "text", value: "0.9" },
  { key: "median_market_source_age_months", kind: "text", value: "7.5" },
  { key: "branches_ok", kind: "text", value: "3" },
  { key: "cheapest_next_test", kind: "text", value: "Offer a paid pilot to three teams already paying for a codegen tool." },
  { key: "kill_criteria", kind: "json", value: "[\n  \"No team will pay before seeing their own design system reproduced\",\n  \"Incumbent free tiers close the quality gap within two quarters\"\n]" },
  { key: "fatal_floors", kind: "json", value: "[]" },
  { key: "composite_score", kind: "text", value: "5.0" },
  { key: "verdict", kind: "text", value: "NEEDS_WORK" },
  { key: "decision_reason", kind: "text", value: "null" },
  { key: "confidence", kind: "text", value: "0.7" },
  { key: "confidence_band", kind: "text", value: "HIGH" },
  { key: "provisional", kind: "text", value: "false" },
]

export function buildMockSegments(runId: string): MockScriptStep[][] {
  let seq = 0
  const startedAt = Date.now()
  const make = (
    kind: FrameKind,
    eventType: string,
    message: string,
    nodeId?: string,
    details: Record<string, unknown> = {},
    level: FrameLevel = 'INFO',
    durationMs?: number,
    delayMs = 460,
  ): MockScriptStep => {
    seq += 1
    return {
      delayMs,
      frame: {
        v: 1,
        seq,
        run_id: runId,
        ts: new Date(startedAt + seq * 720).toISOString(),
        kind,
        event_type: eventType,
        level,
        node_id: nodeId,
        message,
        details,
        duration_ms: durationMs,
      },
    }
  }

  return [
    [
      make('run_state', 'RUN_QUEUED', 'Run accepted and queued.', undefined, { status: 'queued' }, 'INFO', undefined, 180),
      make('run_state', 'RUN_STARTED', 'Validator run started.', undefined, { status: 'running' }, 'INFO', undefined, 380),
      make('node_state', 'NODE_START', 'Parsing the idea into testable claims.', NODE.scope),
      make('llm', 'LLM_CALL_STARTED', 'Scoper is structuring the validation scope.', NODE.scope, { stage: 'before', call_id: 'scope-llm', model: 'escalation' }),
      make('token', 'TOKEN_USAGE', 'Scope model usage recorded.', NODE.scope, { call_id: 'scope-llm', usage: { prompt_tokens: 682, completion_tokens: 241, total_tokens: 923, cost_usd: 0.0048 } }),
      make('llm', 'LLM_CALL_COMPLETED', 'Three independent research questions are ready.', NODE.scope, { stage: 'after', call_id: 'scope-llm', model: 'escalation' }, 'INFO', 2840),
      make('node_state', 'NODE_END', 'Scope prepared for operator review.', NODE.scope, {}, 'INFO', 3310),
      make('edge_taken', 'EDGE_TRAVERSED', 'Scope moved to operator review.', undefined, { from: NODE.scope, to: NODE.scopeGate }),
      make('node_state', 'NODE_WAITING', 'Waiting for scope confirmation.', NODE.scopeGate),
      make('gate_open', 'HUMAN_INTERACTION', 'Confirm scope', NODE.scopeGate, {
        gate_id: SCOPE_GATE_ID,
        node_id: NODE.scopeGate,
        title: 'Confirm scope',
        summary: 'Design-to-code tooling',
        editable: true,
        expires_at: new Date(startedAt + 10 * 60 * 1000).toISOString(),
        fields: SCOPE_FIELDS,
        derived: [],
        options: [
          { id: 'approve', label: 'Approve', emphasis: 'primary' },
          { id: 'revise', label: 'Revise' },
        ],
      }, 'WARNING', undefined, 520),
    ],
    [
      make('gate_closed', 'GATE_CLOSED', 'Scope approved.', NODE.scopeGate, { gate_id: SCOPE_GATE_ID, outcome: 'approve' }, 'INFO', undefined, 220),
      make('node_state', 'NODE_END', 'Scope gate approved.', NODE.scopeGate),
      make('edge_taken', 'EDGE_TRAVERSED', 'Reply handed to the scope router.', undefined, { from: NODE.scopeGate, to: NODE.scopeRouter }, 'INFO', undefined, 160),
      // The router is deterministic: it reads the reply and emits an event.
      // It is on the graph because the run passes through it, and it finishes
      // in milliseconds because it never calls a model.
      make('node_state', 'NODE_START', 'Routing the approved scope.', NODE.scopeRouter, {}, 'INFO', undefined, 140),
      make('node_state', 'NODE_END', 'Routed to scope_approved with no model call.', NODE.scopeRouter, { route: 'scope_approved' }, 'INFO', 4, 160),
      make('edge_taken', 'EDGE_TRAVERSED', 'Market branch released.', undefined, { from: NODE.scopeRouter, to: NODE.market }, 'INFO', undefined, 140),
      make('edge_taken', 'EDGE_TRAVERSED', 'Demand branch released.', undefined, { from: NODE.scopeRouter, to: NODE.sentiment }, 'INFO', undefined, 140),
      make('edge_taken', 'EDGE_TRAVERSED', 'Feasibility branch released.', undefined, { from: NODE.scopeRouter, to: NODE.feasibility }, 'INFO', undefined, 140),
      make('node_state', 'NODE_START', 'Mapping category, segments, and pricing.', NODE.market),
      make('node_state', 'NODE_START', 'Searching for pain and maintained workarounds.', NODE.sentiment, {}, 'INFO', undefined, 120),
      make('node_state', 'NODE_START', 'Checking implementation paths and incumbents.', NODE.feasibility, {}, 'INFO', undefined, 120),
      make('tool', 'TOOL_CALL_STARTED', 'firecrawl.search · design-to-code market', NODE.market, { stage: 'before', tool: 'firecrawl.search' }),
      make('tool', 'TOOL_CALL_STARTED', 'hn.search · Figma handoff pain', NODE.sentiment, { stage: 'before', tool: 'hn.search' }, 'INFO', undefined, 160),
      make('tool', 'TOOL_CALL_STARTED', 'github.search_repositories · figma react', NODE.feasibility, { stage: 'before', tool: 'github.search_repositories' }, 'INFO', undefined, 160),
      make('tool', 'TOOL_CALL_COMPLETED', '12 market sources retained after dedupe.', NODE.market, { stage: 'after', tool: 'firecrawl.search', from_cache: false }, 'INFO', 4160, 780),
      make('tool', 'TOOL_CALL_COMPLETED', '7 relevant threads classified; 2 are weak.', NODE.sentiment, { stage: 'after', tool: 'hn.search', from_cache: false }, 'WARNING', 3290, 420),
      make('tool', 'TOOL_CALL_COMPLETED', '18 repositories checked for maintenance and licensing.', NODE.feasibility, { stage: 'after', tool: 'github.search_repositories', from_cache: false }, 'INFO', 3670, 420),
      make('token', 'TOKEN_USAGE', 'Parallel analyst usage recorded.', undefined, { usage: { promptTokens: 4210, completionTokens: 1684, totalTokens: 5894, costUsd: 0.0061 } }),
      make('node_state', 'NODE_END', 'Market landscape complete.', NODE.market, {}, 'INFO', 6120),
      make('node_state', 'NODE_END', 'Demand evidence complete with two thin signals.', NODE.sentiment, {}, 'WARNING', 5840, 120),
      make('node_state', 'NODE_END', 'Technical feasibility assessment complete.', NODE.feasibility, {}, 'INFO', 5930, 120),
      make('edge_taken', 'EDGE_TRAVERSED', 'Market evidence joined synthesis.', undefined, { from: NODE.market, to: NODE.synthesis }),
      make('edge_taken', 'EDGE_TRAVERSED', 'Demand evidence joined synthesis.', undefined, { from: NODE.sentiment, to: NODE.synthesis }, 'INFO', undefined, 130),
      make('edge_taken', 'EDGE_TRAVERSED', 'Feasibility evidence joined synthesis.', undefined, { from: NODE.feasibility, to: NODE.synthesis }, 'INFO', undefined, 130),
      make('node_state', 'NODE_START', 'Applying the deterministic five-dimension rubric.', NODE.synthesis),
      make('llm', 'LLM_CALL_STARTED', 'Synthesist is reconciling evidence and score anchors.', NODE.synthesis, { stage: 'before', call_id: 'synthesis-llm', model: 'escalation' }),
      make('token', 'TOKEN_USAGE', 'Synthesis usage recorded.', NODE.synthesis, { call_id: 'synthesis-llm', usage: { prompt_tokens: 3028, completion_tokens: 812, total_tokens: 3840, cost_usd: 0.0126 } }),
      make('llm', 'LLM_CALL_COMPLETED', 'Draft verdict: NEEDS_WORK · confidence 0.70.', NODE.synthesis, { stage: 'after', call_id: 'synthesis-llm', model: 'escalation' }, 'INFO', 4210),
      make('node_state', 'NODE_END', 'Rubric scored and confidence separated.', NODE.synthesis, {}, 'INFO', 4680),
      make('edge_taken', 'EDGE_TRAVERSED', 'Draft verdict moved to operator review.', undefined, { from: NODE.synthesis, to: NODE.verdictGate }),
      make('node_state', 'NODE_WAITING', 'Waiting for verdict review.', NODE.verdictGate),
      make('metrics', 'METRICS_UPDATED', 'Run metrics updated.', undefined, { elapsed_ms: 18420, call_count: 5 }),
      make('gate_open', 'HUMAN_INTERACTION', 'Review verdict', NODE.verdictGate, {
        gate_id: VERDICT_GATE_ID,
        node_id: NODE.verdictGate,
        title: 'Review verdict',
        summary: 'Offer a paid pilot to three teams already paying for a codegen tool.',
        verdict: 'NEEDS_WORK',
        confidence: 0.7,
        editable: true,
        expires_at: new Date(startedAt + 20 * 60 * 1000).toISOString(),
        fields: VERDICT_FIELDS,
        derived: VERDICT_DERIVED,
        options: [
          { id: 'approve', label: 'Approve', emphasis: 'primary' },
          { id: 'revise', label: 'Revise' },
        ],
      }, 'WARNING'),
    ],
    [
      make('gate_closed', 'GATE_CLOSED', 'Verdict accepted.', NODE.verdictGate, { gate_id: VERDICT_GATE_ID, outcome: 'approve' }, 'INFO', undefined, 220),
      make('node_state', 'NODE_END', 'Verdict gate approved.', NODE.verdictGate),
      make('edge_taken', 'EDGE_TRAVERSED', 'Reply handed to the verdict router.', undefined, { from: NODE.verdictGate, to: NODE.verdictRouter }, 'INFO', undefined, 160),
      make('node_state', 'NODE_START', 'Routing the accepted verdict.', NODE.verdictRouter, {}, 'INFO', undefined, 140),
      make('node_state', 'NODE_END', 'Routed to verdict_approved with no model call.', NODE.verdictRouter, { route: 'verdict_approved' }, 'INFO', 3, 160),
      make('edge_taken', 'EDGE_TRAVERSED', 'Reporter released.', undefined, { from: NODE.verdictRouter, to: NODE.report }),
      make('node_state', 'NODE_START', 'Writing the sourced one-page validation brief.', NODE.report),
      make('llm', 'LLM_CALL_STARTED', 'Reporter is composing the brief and attribution table.', NODE.report, { stage: 'before', call_id: 'report-llm', model: 'escalation' }),
      make('token', 'TOKEN_USAGE', 'Reporter usage recorded.', NODE.report, { call_id: 'report-llm', usage: { prompt_tokens: 2489, completion_tokens: 1054, total_tokens: 3543, cost_usd: 0.0157 } }),
      make('llm', 'LLM_CALL_COMPLETED', 'Brief passed mechanics and source attribution checks.', NODE.report, { stage: 'after', call_id: 'report-llm', model: 'escalation' }, 'INFO', 3890),
      make('node_state', 'NODE_END', 'Validation brief written.', NODE.report, {}, 'INFO', 4290),
      make('edge_taken', 'EDGE_TRAVERSED', 'Validated report published.', undefined, { from: NODE.report, to: NODE.output }),
      make('node_state', 'NODE_END', 'output/validation.md is ready.', NODE.output),
      make('metrics', 'METRICS_UPDATED', 'Final usage and cost calculated.', undefined, { elapsed_ms: 27430, call_count: 7 }),
      make('run_state', 'RUN_COMPLETED', 'Run completed with a NEEDS_WORK verdict.', undefined, { status: 'completed' }, 'INFO', 27430),
    ],
  ]
}
