import { computed, ref, shallowRef } from 'vue'
import { API_BASE_URL } from '../services/httpCore'
import type { ModelRoster, RegistryModel, SpeedTier } from '../types/builder'

/**
 * The model roster, fetched once per session from `GET /api/builder/models`.
 *
 * SERVED RATHER THAN DUPLICATED, and the reason is sharper here than it is for
 * the vocabulary. The roster is DATA - ten rows of catalogue facts nobody in
 * this repository decides - and a hardcoded copy has nothing to disagree with
 * except the file it was copied from. A stale copy would price a graph in the
 * budget meter at yesterday's numbers while the server refused it at today's,
 * and the author would see a meter that said one thing and a refusal that said
 * another with no way to tell which was lying.
 *
 * THERE IS NO FALLBACK LIST, exactly as `builderVocabulary.ts` has none. When
 * the fetch fails the picker disables and states the reason, which is the one
 * honest answer available: a client-side roster is how a canvas starts offering
 * models the compiler has never heard of.
 *
 * NO AUTH, deliberately. `get_models` carries no `Depends(current_user)` - it
 * describes this BUILD, not anybody's data - and it has to resolve before the
 * three-phase auth gate does, or the inspector's model picker is empty for the
 * whole of a sign-in.
 *
 * `frontend/tests/fixtures/models.json` is generated by
 * `scripts/emit_builder_fixtures.py` through the same `registry_document` the
 * endpoint serves, and `tests/builder/test_client_fixtures.py` byte-compares it
 * against what is committed. That is spec ruling R7's condition for admitting a
 * client mirror at all.
 */

/** `service/builder_api.py:BUILDER_API_PREFIX` + the handler's own path. */
export const MODELS_PATH = '/api/builder/models'

/**
 * `sessionStorage`, not `localStorage`, and beside the vocabulary for one reason.
 *
 * The roster describes ONE BUILD of the server, and both Render services carry
 * `autoDeploy: yes`, so a build can change under an open browser. A
 * session-scoped cache survives a reload - which is what it is for: a reload
 * should not blank the picker while a request is in flight - and dies with the
 * tab.
 */
const SESSION_KEY = 'builder-models'

/** The loaded roster, or null while it has not loaded. Replaced whole, never mutated. */
export const roster = shallowRef<ModelRoster | null>(null)

/**
 * Why the roster is unusable, as a sentence, or `''` when it is fine.
 *
 * One writable fact with two readers, the same shape `vocabularyProblem` uses:
 * the picker needs a boolean to disable and a `role="alert"` needs a string,
 * and holding those as two refs is holding one fact twice.
 */
export const rosterProblem = ref('')

/** True once a load has been attempted and failed. Never merely because nothing has loaded. */
export const rosterUnavailable = computed(() => rosterProblem.value !== '')

/** The single in-flight request, so N pickers mounting at once make one fetch. */
let inFlight: Promise<ModelRoster | null> | null = null

/**
 * The roster, fetching it at most once per session.
 *
 * Resolves to `null` on failure rather than rejecting: every caller is a
 * component mounting, so a rejected promise would be an unhandled rejection in
 * a `setup()` and the picker would still have to read `rosterProblem` to know
 * what to say. The reason is the return value that matters.
 */
export function loadModels(): Promise<ModelRoster | null> {
  if (roster.value) return Promise.resolve(roster.value)
  if (inFlight) return inFlight

  const cached = readSession()
  if (cached) {
    roster.value = cached
    rosterProblem.value = ''
    return Promise.resolve(cached)
  }

  inFlight = fetchModels().finally(() => {
    inFlight = null
  })
  return inFlight
}

/**
 * Drop everything loaded and let the next `loadModels()` start again.
 *
 * Exported for tests, and honest about it: a module singleton outlives one spec
 * file's expectations, and a cache that cannot be cleared makes the second test
 * in a file depend on the first.
 */
export function resetModels(): void {
  roster.value = null
  rosterProblem.value = ''
  inFlight = null
  try {
    window.sessionStorage.removeItem(SESSION_KEY)
  } catch {
    /* Private mode, or storage disabled. Never a reason to fail. */
  }
}

async function fetchModels(): Promise<ModelRoster | null> {
  let payload: unknown
  try {
    // A plain `fetch`, not `authedFetch`: this endpoint is open, and waiting on
    // a bearer mint would make the picker empty for the whole of a sign-in.
    const response = await fetch(`${API_BASE_URL}${MODELS_PATH}`, {
      headers: { Accept: 'application/json' },
    })
    if (!response.ok) {
      return refuse(
        `The model roster could not be loaded: the API answered ${response.status} ${response.statusText}.`,
      )
    }
    payload = await response.json()
  } catch (error) {
    /*
     * One catch, two diagnoses, told apart by the message: a `TypeError` from
     * `fetch` is an unreachable API, a `SyntaxError` from `json()` is an API
     * that answered something that is not JSON - which in this codebase
     * overwhelmingly means `VITE_API_URL` was unset and the SPA's own history
     * fallback answered 200 text/html (deployment trap 2).
     */
    return refuse(
      `The model roster could not be loaded: ${(error as Error)?.message ?? 'network error'}.`,
    )
  }

  const parsed = normalise(payload)
  if (typeof parsed === 'string') return refuse(parsed)

  roster.value = parsed
  rosterProblem.value = ''
  writeSession(parsed)
  return parsed
}

function refuse(reason: string): null {
  roster.value = null
  rosterProblem.value = reason
  return null
}

const SPEED_TIERS: readonly SpeedTier[] = ['fast', 'balanced', 'deep']

/**
 * A payload turned into a `ModelRoster`, or the sentence saying why not.
 *
 * Every field is read out BY NAME rather than spread, the same discipline
 * `builderVocabulary.ts` applies: what this build knows how to render is
 * visible in one place, and a key the server grows arrives as a key nothing
 * renders rather than as an untyped passenger.
 *
 * The checks are not defensive noise. An empty `models` disables every model
 * control while claiming a roster loaded; a non-finite price puts `$NaN` in the
 * budget meter; a row over the served ceiling is a row the server would refuse
 * at publish, so offering it in a picker is advertising a document that cannot
 * be saved.
 */
function normalise(payload: unknown): ModelRoster | string {
  if (!payload || typeof payload !== 'object') {
    return 'The model roster could not be loaded: the API answered something that is not an object.'
  }
  const raw = payload as Record<string, unknown>
  const ceiling = Number(raw.ceiling_usd_per_m_input)
  if (!Number.isFinite(ceiling) || ceiling <= 0) {
    return 'The model roster could not be loaded: it declares no usable price ceiling.'
  }

  const rows = raw.models
  if (!Array.isArray(rows) || rows.length === 0) {
    return 'The model roster could not be loaded: it lists no models.'
  }

  const models: RegistryModel[] = []
  for (const entry of rows) {
    const model = normaliseModel(entry, ceiling)
    if (typeof model === 'string') return model
    models.push(model)
  }

  const presets: Record<string, string> = {}
  const rawPresets = (raw.presets ?? {}) as Record<string, unknown>
  const ids = new Set(models.map((model) => model.id))
  for (const [tier, spelling] of Object.entries(rawPresets)) {
    const value = String(spelling)
    // Resolved variant-stripped, because a preset legitimately carries `:nitro`
    // and the rows never do. A preset that resolves to nothing would leave the
    // tier control unable to say what it costs.
    if (!ids.has(baseSlug(value))) {
      return `The model roster could not be loaded: the ${tier} preset names ${value}, which is not one of its models.`
    }
    presets[tier] = value
  }

  return {
    schema: String(raw.schema ?? ''),
    generated_at: String(raw.generated_at ?? ''),
    source: String(raw.source ?? ''),
    ceiling_usd_per_m_input: ceiling,
    presets,
    models,
  }
}

function normaliseModel(entry: unknown, ceiling: number): RegistryModel | string {
  if (!entry || typeof entry !== 'object') {
    return 'The model roster could not be loaded: one of its models is not an object.'
  }
  const raw = entry as Record<string, unknown>
  const id = String(raw.id ?? '')
  if (!id) return 'The model roster could not be loaded: a model has no id.'

  const cost_in = Number(raw.cost_in)
  const cost_out = Number(raw.cost_out)
  const cost_in_max_endpoint = Number(raw.cost_in_max_endpoint)
  if (![cost_in, cost_out, cost_in_max_endpoint].every(Number.isFinite)) {
    return `The model roster could not be loaded: ${id} has a price that is not a number.`
  }
  if (cost_in > ceiling) {
    return `The model roster could not be loaded: ${id} is $${cost_in}/M input, over the $${ceiling}/M ceiling this build enforces.`
  }
  const speed = String(raw.speed_tier ?? '') as SpeedTier
  if (!SPEED_TIERS.includes(speed)) {
    return `The model roster could not be loaded: ${id} declares an unknown speed tier ${String(raw.speed_tier)}.`
  }

  return {
    id,
    name: String(raw.name ?? id),
    provider: String(raw.provider ?? id.split('/')[0]),
    context_window: Number(raw.context_window) || 0,
    supports_tools: raw.supports_tools === true,
    supports_vision: raw.supports_vision === true,
    supports_json_mode: raw.supports_json_mode === true,
    supports_reasoning: raw.supports_reasoning === true,
    cost_in,
    cost_out,
    cost_in_max_endpoint,
    speed_tier: speed,
    recommended_for: Array.isArray(raw.recommended_for)
      ? raw.recommended_for.map(String)
      : [],
  }
}

/**
 * A model id reduced to the registry's own spelling: no prefix, no variant.
 *
 * Four spellings reach this codebase - `config.py` writes one, CrewAI reports
 * another, a preset carries a third, a hand-edited document a fourth - and only
 * one of them is a key. `resolve_price_model`'s docstring is the history of
 * getting this wrong; it cost a run priced at $0.00 over 128,069 real tokens.
 */
export function baseSlug(model: string): string {
  const withoutPrefix = String(model ?? '').replace(/^openrouter\//, '')
  const colon = withoutPrefix.lastIndexOf(':')
  return colon > 0 ? withoutPrefix.slice(0, colon) : withoutPrefix
}

/** The roster row a model id names, in any of the four spellings, or null. */
export function modelById(id: string): RegistryModel | null {
  const wanted = baseSlug(id)
  return roster.value?.models.find((model) => model.id === wanted) ?? null
}

/** The row a tier's preset resolves to, or null when the roster has not loaded. */
export function modelForTier(tier: string): RegistryModel | null {
  const spelling = roster.value?.presets[tier]
  return spelling ? modelById(spelling) : null
}

/**
 * What a `:nitro` id may bill above its published rate, as a factor.
 *
 * Mirrors `budget.py::_nitro_multiplier` and is the ONE piece of pricing
 * arithmetic this client does, for one reason: it is what lets the picker
 * explain why the meter shows more than the headline implies. Nitro routes on
 * SPEED, not price, so a nitro id's published rate is a floor and the dearest
 * endpoint is what it can cost. A plain id gets 1.0 - applying a factor to one
 * would invent a number in both directions, since the measured per-model
 * spreads run 1.1x for the three OpenAI first-party rows to 9.5x for
 * `openai/gpt-oss-120b`.
 *
 * It is NOT used to price a graph. The budget meter renders the SERVER's
 * figure; a second estimator here would be a number that quietly disagrees with
 * the one enforcing the ceiling.
 */
export function nitroMultiplier(id: string): number {
  if (!String(id ?? '').toLowerCase().includes(':nitro')) return 1
  const model = modelById(id)
  if (!model || model.cost_in <= 0) return 1
  return model.cost_in_max_endpoint / model.cost_in
}

function readSession(): ModelRoster | null {
  let stored: string | null = null
  try {
    stored = window.sessionStorage.getItem(SESSION_KEY)
  } catch {
    // Private mode, or a browser refusing site data. The cache is a
    // convenience; the fetch is the source of truth.
    return null
  }
  if (!stored) return null
  try {
    const parsed = normalise(JSON.parse(stored))
    return typeof parsed === 'string' ? null : parsed
  } catch {
    // A half-written or older-shaped entry is discarded rather than repaired.
    return null
  }
}

function writeSession(value: ModelRoster): void {
  try {
    window.sessionStorage.setItem(SESSION_KEY, JSON.stringify(value))
  } catch {
    // Quota, private mode, or storage disabled. Losing the cache costs one
    // request per reload and nothing else, so it must never break a load.
  }
}
