import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

import { PROBLEM_CODES, WARNING_CODES } from '../src/types/builder'
import type { BuilderDocument, ProblemCode } from '../src/types/builder'
import { backEdges } from '../src/utils/builderGraph'
import { everyProblemInstance, vocabularyFixture } from './helpers'
import backEdgeFixture from './fixtures/builderBackEdges.json'

/**
 * The three places this client restates something the server owns, held to what
 * the server actually says.
 *
 * Every one of them is invisible when it goes wrong, which is the only reason
 * they are worth a file of their own:
 *
 * 1. **`backEdges`** is a line-for-line mirror of `bounds._back_edges_with_index`
 *    and exists so a cycle is LEGIBLE (spec R7). A wrong answer raises nothing.
 *    The edge simply stops being dashed, or the wrong one starts being, and the
 *    author reads a graph that is not the one the compiler sees.
 * 2. **`PROBLEM_CODES`** decides which surface renders a problem. A code the
 *    tuple has never heard of still renders its sentence - the `| string`
 *    fallback is deliberate - but `FIELD_CODES` cannot place it and no surface
 *    is written for it, so the document refuses to publish with nothing on
 *    screen saying why.
 * 3. **`vocabularyFixture()`** is a hand-written copy of a served payload, and
 *    every test that asserts a bound reads it. A bound that moves on the server
 *    would leave the whole builder suite green over the old number - the exact
 *    shape of the `serverLimits.ts` hazard, one layer deeper.
 *
 * The first two are pinned against fixtures generated by
 * `scripts/emit_builder_fixtures.py` from the real Python functions, and
 * `tests/builder/test_client_fixtures.py` regenerates and byte-compares those
 * fixtures in the Python suite. That pairing is the anti-drift gate: this file
 * proves the client agrees with the fixture, and the Python file proves the
 * fixture agrees with the server. Neither half alone is worth anything - a
 * mirror checked against a stale copy of its original is not checked.
 *
 * The third is pinned by reading the Python source directly, which is the
 * `serverLimits.ts` idiom this repository already blesses. It is used here
 * rather than a third fixture for one specific reason: `MAX_RUN_COST_USD` is
 * `_env_non_negative_float(..., 10.0)`, so a generated copy of the vocabulary
 * would differ between two machines whose shells differ, and a drift gate that
 * reports the environment is worse than none.
 */

/**
 * A Python source file, read at test time.
 *
 * The relative path goes through a variable deliberately. Vite rewrites
 * `new URL('<literal>', import.meta.url)` into an ASSET url at transform time,
 * so a literal here resolves to an http scheme and `fileURLToPath` refuses it;
 * a variable is opaque to that transform and the expression stays what it
 * reads as. `builderGraph.spec.ts` and `builderTypes.spec.ts` both do the same,
 * for the same reason.
 */
function pythonSource(relative: string): string {
  return readFileSync(fileURLToPath(new URL(relative, import.meta.url)), 'utf-8')
}

/* --- 1. the back-edge mirror --------------------------------------------- */

interface BackEdgeCase {
  name: string
  why: string
  document: BuilderDocument
  permutations: Array<{ order: number[]; back_edge_indices: number[] }>
}

const BACK_EDGE_CASES = (backEdgeFixture as unknown as { cases: BackEdgeCase[] }).cases

describe('the back-edge mirror answers what bounds.py answered', () => {
  it('covers every case in the fixture under every ordering it records', () => {
    // Counted rather than trusted. A fixture that silently emptied - a
    // generator refactor, a bad merge - would make every assertion below vacuous
    // and this file would still report a pass.
    let checked = 0
    for (const testCase of BACK_EDGE_CASES) {
      for (const permutation of testCase.permutations) {
        const permuted: BuilderDocument = {
          ...testCase.document,
          edges: permutation.order.map((index) => testCase.document.edges[index]),
        }
        expect(
          backEdges(permuted),
          `${testCase.name} @ [${permutation.order.join(',')}]`,
        ).toEqual(permutation.back_edge_indices)
        checked += 1
      }
    }
    expect(checked).toBeGreaterThan(200)
  })

  it('is order-sensitive, which is why the fixture is permuted at all', () => {
    /*
     * The mirror returns POSITIONS in `doc.edges`, and the whole reason R7 asks
     * for order-permuted documents is that two parallel edges between one pair
     * are equal as values - only the position tells them apart. If every
     * ordering gave the same answer, the assertion above would be satisfied by
     * a mirror that ignored edge order entirely, which is a real way to write
     * this function and a wrong one.
     */
    const answers = new Set(
      BACK_EDGE_CASES.flatMap((testCase) =>
        testCase.permutations.map((row) => row.back_edge_indices.join(',')),
      ),
    )
    expect(answers.size).toBeGreaterThan(1)
  })

  it('agrees that an acyclic graph closes nothing', () => {
    // The negative case, stated separately because it is the one a mirror that
    // returned every edge would fail and a mirror that returned nothing would
    // pass. Both halves have to be asserted or neither is.
    const acyclic = BACK_EDGE_CASES.find((testCase) =>
      testCase.permutations.every((row) => row.back_edge_indices.length === 0),
    )
    expect(acyclic, 'no acyclic case in the fixture').toBeDefined()
    expect(backEdges(acyclic!.document)).toEqual([])
  })
})

/* --- 2. the problem-code mirror ------------------------------------------ */

describe('the problem-code tuple covers what the server can emit', () => {
  const instances = everyProblemInstance()

  it('lists exactly the codes the server produced, in both directions', () => {
    const fromServer = instances.map((instance) => instance.code).sort()
    expect([...PROBLEM_CODES].sort()).toEqual(fromServer)
  })

  it('carries one instance per code and no duplicates', () => {
    const codes = instances.map((instance) => instance.code)
    expect(new Set(codes).size).toBe(codes.length)
  })

  it('names exactly the three warnings and marks everything else an error', () => {
    /*
     * `WARNING_CODES` is what `ProblemsPanel`'s empty state promises in one
     * sentence: warnings never block, errors always do. A code that quietly
     * became a warning on the server while this tuple still called it an error
     * would leave Publish disabled with a problem list the author has been told
     * is harmless.
     */
    const warnings = instances
      .filter((instance) => instance.problem.severity === 'warning')
      .map((instance) => instance.code)
      .sort()
    expect([...WARNING_CODES].sort()).toEqual(warnings)
  })

  it('renders every message as a whole sentence, never an empty row', () => {
    for (const instance of instances) {
      expect(instance.problem.message.length, instance.code).toBeGreaterThan(30)
      expect(instance.problem.message.trim()).toBe(instance.problem.message)
    }
  })

  it('anchors a problem to a node, an edge, both, or neither - and says which', () => {
    /*
     * The three-way split is the whole of §6.3. A code anchoring BOTH a node and
     * an edge has to be entered in both indexes or one of the two surfaces
     * silently drops it; a code anchoring NEITHER belongs to the document group
     * and has no node to centre on. Enumerating the both-anchor set here is what
     * makes `useBuilderProblems`' double entry checkable rather than assumed.
     */
    const both = instances
      .filter(
        (instance) =>
          instance.problem.node_id !== null && instance.problem.edge_id !== null,
      )
      .map((instance) => instance.code)
      .sort()
    expect(both).toEqual(['back-edge-not-router', 'edge-target-refuses-incoming', 'edge-unknown-port'])

    const neither = instances
      .filter(
        (instance) =>
          instance.problem.node_id === null && instance.problem.edge_id === null,
      )
      .map((instance) => instance.code)
      .sort()
    expect(neither).toEqual([
      'billable-count',
      'budget-over-ceiling',
      'budget-unpriced-model',
      'ident-collision',
      'input-field-undeclared',
      'join-unknown-node',
      'no-input-node',
      'no-output-node',
      'node-count',
    ])
  })

  it('types every fixture code as a known ProblemCode', () => {
    // A compile-time assertion with a runtime witness. The cast is the claim;
    // the loop is what makes a wrong claim fail rather than merely compile.
    const known = new Set<string>(PROBLEM_CODES)
    for (const instance of instances) {
      const code = instance.code as ProblemCode
      expect(known.has(code), code).toBe(true)
    }
  })
})

/* --- 3. the vocabulary copy ---------------------------------------------- */

const CONFIG = pythonSource('../../src/brief_crew/config.py')
const BUILDER_API = pythonSource('../../src/brief_crew/service/builder_api.py')
const RUNTIME = pythonSource('../../src/brief_crew/builder/runtime.py')

/**
 * The value of a module-level constant in `config.py`.
 *
 * Three declaration shapes, and each is one of the fifteen bounds rather than
 * defensive breadth: a plain integer, `256 * 1024`, and
 * `_env_non_negative_float("MAX_RUN_COST_USD", 10.0)` - whose DEFAULT is read,
 * because the default is what a deployment that sets nothing runs on and is the
 * only value a fixture can honestly claim. A shape this does not recognise
 * throws naming the constant, so a new spelling fails loudly here rather than
 * quietly returning NaN and comparing equal to nothing.
 */
function configConstant(name: string): number {
  const declaration = new RegExp(`^${name} = (.+)$`, 'm').exec(CONFIG)
  if (!declaration) throw new Error(`config.py declares no ${name}`)
  const expression = declaration[1].split('#')[0].trim()

  if (/^\d+$/.test(expression)) return Number(expression)

  const product = /^(\d+) \* (\d+)$/.exec(expression)
  if (product) return Number(product[1]) * Number(product[2])

  const envDefault = /^_env_[a-z_]+\("[A-Z_]+", ([0-9.]+)\)$/.exec(expression)
  if (envDefault) return Number(envDefault[1])

  throw new Error(`${name} is declared as ${expression!}, a shape this test cannot read`)
}

/** Every `"key": project_config.NAME` pair in `_vocabulary`'s bounds block. */
function boundsMapping(): Map<string, string> {
  const block = /bounds=\{([\s\S]*?)\n {8}\},/.exec(BUILDER_API)
  if (!block) throw new Error('builder_api.py::_vocabulary has no readable bounds block')
  const pairs = new Map<string, string>()
  for (const match of block[1].matchAll(/"([a-z_]+)": project_config\.([A-Z_]+),/g)) {
    pairs.set(match[1], match[2])
  }
  return pairs
}

/** The keys of a `NAME: Mapping[...] = { "a": ..., }` literal in `runtime.py`. */
function mappingKeys(name: string): string[] {
  const block = new RegExp(`^${name}[^=]*= \\{([\\s\\S]*?)\\n\\}`, 'm').exec(RUNTIME)
  if (!block) throw new Error(`runtime.py declares no readable ${name}`)
  return [...block[1].matchAll(/^ {4}"([a-z_]+)":/gm)].map((match) => match[1])
}

/** The string members of a `NAME: frozenset[str] = frozenset({...})` in `config.py`. */
function frozensetMembers(name: string): string[] {
  const block = new RegExp(`^${name}[^=]*= frozenset\\(([\\s\\S]*?)\\n\\)`, 'm').exec(CONFIG)
  if (!block) throw new Error(`config.py declares no readable ${name}`)
  return [...block[1].matchAll(/"([a-z_]+)"/g)].map((match) => match[1])
}

describe('the vocabulary fixture is what this build would serve', () => {
  const served = vocabularyFixture()

  it('carries every bound the handler publishes, at the value config.py declares', () => {
    const mapping = boundsMapping()
    expect(mapping.size, 'the bounds block moved shape').toBe(15)

    for (const [key, constant] of mapping) {
      expect(
        served.bounds[key as keyof typeof served.bounds],
        `${key} is ${constant} in config.py`,
      ).toBe(configConstant(constant))
    }

    // Both directions. A bound the handler stopped publishing would otherwise
    // sit in the fixture forever, and a test reading it would be asserting
    // against a key no response carries.
    expect(Object.keys(served.bounds).sort()).toEqual([...mapping.keys()].sort())
  })

  it('offers exactly the registered agents', () => {
    expect(served.agent_ids).toEqual(mappingKeys('BUILDER_AGENT_LIBRARY').sort())
  })

  it('offers the buildable crews and withholds the two that raise at run time', () => {
    /*
     * `synthesis` and `report` are registered and are NOT vocabulary.
     * `SynthesisCrew(market, sentiment, feasibility)` and
     * `ReportCrew(verdict, tool_urls)` take typed findings a drawn document
     * cannot express, so a document naming one validated clean, published
     * clean, was priced and registered - and raised a bare TypeError at the
     * first PAID run, after the scoper and all three research branches had
     * billed.
     */
    const unbuildable = new Set(mappingKeys('UNBUILDABLE_BUILDER_CREWS'))
    expect([...unbuildable].sort()).toEqual(['report', 'synthesis'])
    expect(served.crew_ids).toEqual(
      mappingKeys('BUILDER_CREW_LIBRARY')
        .filter((id) => !unbuildable.has(id))
        .sort(),
    )
  })

  it('offers exactly the research tools, transform ops and router comparisons', () => {
    expect(served.research_tools).toEqual(frozensetMembers('BUILDER_RESEARCH_TOOLS').sort())
    expect(served.transform_ops).toEqual(frozensetMembers('BUILDER_TRANSFORM_OPS').sort())
    expect(served.router_comparisons).toEqual(
      frozensetMembers('BUILDER_ROUTER_COMPARISONS').sort(),
    )
    expect(served.router_comparisons).not.toContain('otherwise')
  })

  it('spells the schema id, the otherwise branch and the body key the way the server does', () => {
    expect(CONFIG).toContain(`BUILDER_DOCUMENT_SCHEMA = "${served.schema_id}"`)
    expect(CONFIG).toContain(`BUILDER_ROUTER_OTHERWISE = "${served.router_otherwise}"`)
    expect(CONFIG).toContain(
      `RUN_RESULT_BODY_KEYS: tuple[str, ...] = ("${served.result_body_keys[0]}",)`,
    )
    expect(served.result_body_keys).toHaveLength(1)
  })

  it('lists the node kinds in the handler order rather than sorted', () => {
    /*
     * The palette renders `node_kinds` in the order it is served (§2, WP-D), so
     * a fixture that sorted them would test a palette nobody ships - `agent`
     * first, `input` third. The handler writes the seven as literals; this reads
     * that literal list back.
     */
    const declared = /node_kinds=\[([^\]]+)\]/.exec(BUILDER_API)
    expect(declared, '_vocabulary no longer writes node_kinds as a literal list').toBeTruthy()
    expect([...declared![1].matchAll(/"([a-z]+)"/g)].map((match) => match[1])).toEqual(
      served.node_kinds,
    )
  })
})
