import { mount } from '@vue/test-utils'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'

import ModelPicker from '../src/components/builder/inspectors/ModelPicker.vue'
import {
  MODELS_PATH,
  baseSlug,
  loadModels,
  modelById,
  modelForTier,
  nitroMultiplier,
  resetModels,
  roster,
  rosterProblem,
  rosterUnavailable,
} from '../src/data/models'
import type { ModelRoster } from '../src/types/builder'
import fixture from './fixtures/models.json'

/**
 * The model roster on the client - plan 05, criteria 9 and 10's client half.
 *
 * `fixtures/models.json` is generated by `scripts/emit_builder_fixtures.py`
 * through the SAME `registry_document` that `GET /api/builder/models` serves,
 * and `tests/builder/test_client_fixtures.py` regenerates and byte-compares it
 * in the Python suite. That pairing is the whole anti-drift gate: this file
 * proves the client agrees with the fixture, and the Python file proves the
 * fixture agrees with the server. Neither half alone is worth anything - a
 * mirror checked against a stale copy of its original is not checked.
 *
 * WHAT GOES WRONG HERE IS SILENT, which is why it needs a file. A roster that
 * failed to load leaves a picker with no options and no reason on screen; a
 * price read from the wrong column understates every estimate by up to 9.5x; a
 * capability flag ignored puts a control in front of an author whose value the
 * model will accept, bill for and drop.
 */

const ROSTER = fixture as unknown as ModelRoster

function jsonResponse(body: unknown, ok = true, status = 200): Response {
  return {
    ok,
    status,
    statusText: ok ? 'OK' : 'Error',
    json: async () => body,
  } as unknown as Response
}

describe('the roster loader', () => {
  beforeEach(() => {
    resetModels()
  })

  afterEach(() => {
    resetModels()
    vi.unstubAllGlobals()
  })

  it('fetches the open endpoint once and caches the answer for the session', async () => {
    const fetchMock = vi.fn(async (..._args: unknown[]) => jsonResponse(ROSTER))
    vi.stubGlobal('fetch', fetchMock)

    const first = await loadModels()
    const second = await loadModels()

    expect(first?.models).toHaveLength(ROSTER.models.length)
    expect(second).toBe(first)
    expect(fetchMock).toHaveBeenCalledTimes(1)
    expect(String(fetchMock.mock.calls.at(0)?.at(0) ?? '')).toContain(MODELS_PATH)
  })

  it('makes ONE request when several pickers mount at once', async () => {
    /*
     * The in-flight promise, not the cache. Two pickers mounting in the same
     * tick both see `roster.value === null`, so without the shared promise the
     * console would fetch the roster once per model control on the page.
     */
    const fetchMock = vi.fn(async () => jsonResponse(ROSTER))
    vi.stubGlobal('fetch', fetchMock)

    await Promise.all([loadModels(), loadModels(), loadModels()])

    expect(fetchMock).toHaveBeenCalledTimes(1)
  })

  it('states the reason and loads nothing when the API refuses', async () => {
    vi.stubGlobal('fetch', vi.fn(async () => jsonResponse({}, false, 503)))

    expect(await loadModels()).toBeNull()
    expect(roster.value).toBeNull()
    expect(rosterUnavailable.value).toBe(true)
    expect(rosterProblem.value).toContain('503')
  })

  it('names the SyntaxError case, which in this codebase means VITE_API_URL', async () => {
    /*
     * An unset `VITE_API_URL` resolves every `/api` call against the SPA's own
     * origin, where the history fallback answers 200 text/html for anything -
     * deployment trap 2. The failure reads as "the API is down" unless the
     * message carries the parser's own words.
     */
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => ({
        ok: true,
        status: 200,
        statusText: 'OK',
        json: async () => {
          throw new SyntaxError('Unexpected token < in JSON')
        },
      })) as unknown as typeof fetch,
    )

    expect(await loadModels()).toBeNull()
    expect(rosterProblem.value).toContain('Unexpected token')
  })

  it('refuses a roster with no models rather than disabling every control in silence', async () => {
    vi.stubGlobal('fetch', vi.fn(async () => jsonResponse({ ...ROSTER, models: [] })))

    expect(await loadModels()).toBeNull()
    expect(rosterProblem.value).toContain('no models')
  })

  it('refuses a row the server would itself refuse at publish', async () => {
    /*
     * Offering an over-ceiling model in a picker is advertising a document that
     * cannot be saved. The client does not enforce the ceiling - it refuses to
     * render a roster that contradicts the one it was served with.
     */
    const dear = { ...ROSTER.models[0], id: 'openai/o4-mini', cost_in: 1.1 }
    vi.stubGlobal('fetch', vi.fn(async () => jsonResponse({ ...ROSTER, models: [dear] })))

    expect(await loadModels()).toBeNull()
    expect(rosterProblem.value).toContain('over the')
  })

  it('refuses a preset that names no row, because the tier could not be priced', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => jsonResponse({ ...ROSTER, presets: { cheap: 'nobody/nothing' } })),
    )

    expect(await loadModels()).toBeNull()
    expect(rosterProblem.value).toContain('nobody/nothing')
  })

  it('refuses a price that is not a number, rather than rendering $NaN', async () => {
    const broken = { ...ROSTER.models[0], cost_in: 'free' }
    vi.stubGlobal('fetch', vi.fn(async () => jsonResponse({ ...ROSTER, models: [broken] })))

    expect(await loadModels()).toBeNull()
    expect(rosterProblem.value).toContain('not a number')
  })

  it('survives a browser that refuses session storage', async () => {
    vi.stubGlobal('fetch', vi.fn(async () => jsonResponse(ROSTER)))
    const setItem = vi.spyOn(window.sessionStorage, 'setItem').mockImplementation(() => {
      throw new Error('QuotaExceededError')
    })

    expect((await loadModels())?.models).toHaveLength(ROSTER.models.length)
    setItem.mockRestore()
  })

  it('reads a cached roster back without a request', async () => {
    window.sessionStorage.setItem('builder-models', JSON.stringify(ROSTER))
    const fetchMock = vi.fn(async () => jsonResponse(ROSTER))
    vi.stubGlobal('fetch', fetchMock)

    expect((await loadModels())?.models).toHaveLength(ROSTER.models.length)
    expect(fetchMock).not.toHaveBeenCalled()
  })

  it('discards a half-written cache entry rather than repairing it', async () => {
    window.sessionStorage.setItem('builder-models', '{"schema":"models/v1"')
    const fetchMock = vi.fn(async () => jsonResponse(ROSTER))
    vi.stubGlobal('fetch', fetchMock)

    expect((await loadModels())?.models).toHaveLength(ROSTER.models.length)
    expect(fetchMock).toHaveBeenCalledTimes(1)
  })
})

describe('the four spellings of one model id', () => {
  /*
   * `config.py` writes one, CrewAI reports another, a preset carries a third and
   * a hand-edited document a fourth. Only one of them is a key, and resolving
   * the other three is what `resolve_price_model` exists for - getting it wrong
   * once cost a run priced at $0.00 over 128,069 real tokens.
   */
  it('strips the provider prefix and the routing variant', () => {
    expect(baseSlug('openrouter/google/gemini-3.5-flash-lite:nitro')).toBe(
      'google/gemini-3.5-flash-lite',
    )
    expect(baseSlug('google/gemini-3.5-flash-lite:nitro')).toBe('google/gemini-3.5-flash-lite')
    expect(baseSlug('openrouter/google/gemini-3.8-flash')).toBe('google/gemini-3.8-flash')
    expect(baseSlug('google/gemini-3.8-flash')).toBe('google/gemini-3.8-flash')
  })

  it('leaves a bare slug alone and answers empty for nothing', () => {
    expect(baseSlug('')).toBe('')
    expect(baseSlug('qwen/qwen3.7-flash')).toBe('qwen/qwen3.7-flash')
  })
})

describe('reading the loaded roster', () => {
  beforeEach(() => {
    resetModels()
    roster.value = ROSTER
  })

  afterEach(() => {
    resetModels()
  })

  it('resolves a row in every spelling', () => {
    for (const spelling of [
      'google/gemini-3.5-flash-lite',
      'openrouter/google/gemini-3.5-flash-lite',
      'google/gemini-3.5-flash-lite:nitro',
      'openrouter/google/gemini-3.5-flash-lite:nitro',
    ]) {
      expect(modelById(spelling)?.id).toBe('google/gemini-3.5-flash-lite')
    }
  })

  it('answers null for a model the roster does not carry', () => {
    expect(modelById('openai/o4-mini')).toBeNull()
  })

  it('resolves each tier preset to a row', () => {
    expect(modelForTier('cheap')?.id).toBe('google/gemini-3.5-flash-lite')
    expect(modelForTier('escalation')?.id).toBe('google/gemini-3.8-flash')
  })

  it('inflates a nitro id by its MEASURED endpoint spread and nothing else', () => {
    /*
     * 1.8 is a measurement for the cheap preset - $0.54 over $0.30, both
     * measured 2026-09-04 - and a guess for every other row. A plain id gets
     * 1.0: applying a factor to one would invent a number in both directions,
     * since the roster's spreads run 1.1x to 9.5x.
     */
    expect(nitroMultiplier('google/gemini-3.5-flash-lite:nitro')).toBeCloseTo(1.8, 6)
    expect(nitroMultiplier('google/gemini-3.8-flash')).toBe(1)
    expect(nitroMultiplier('qwen/qwen3.7-flash')).toBe(1)
  })
})

describe('the fixture itself', () => {
  /*
   * Criterion 9's client half. The byte-compare lives in the Python suite; what
   * matters here is that the committed fixture can still exercise the things
   * the picker renders. A roster where every flag were true would make the
   * capability tests below pass over a file that cannot fail them.
   */
  it('carries both price columns on every row', () => {
    for (const model of ROSTER.models) {
      expect(Number.isFinite(model.cost_in)).toBe(true)
      expect(Number.isFinite(model.cost_out)).toBe(true)
      expect(model.cost_in_max_endpoint).toBeGreaterThanOrEqual(model.cost_in)
    }
  })

  it('has at least one row lacking reasoning, or the gate renders nowhere', () => {
    expect(ROSTER.models.some((model) => !model.supports_reasoning)).toBe(true)
  })

  it('holds no row over the ceiling it declares', () => {
    for (const model of ROSTER.models) {
      expect(model.cost_in).toBeLessThanOrEqual(ROSTER.ceiling_usd_per_m_input)
    }
  })

  it('records the escalation preset as exposed to a dearer endpoint', () => {
    /*
     * $0.75 headline, $1.35 on its two `priority` endpoints. It is admissible
     * only because `provider.max_price` filters those before routing, and the
     * picker's job is to make that visible rather than to hide it behind the
     * headline.
     */
    const escalation = ROSTER.models.find((model) => model.id === 'google/gemini-3.8-flash')
    expect(escalation?.cost_in).toBe(0.75)
    expect(escalation?.cost_in_max_endpoint).toBe(1.35)
    expect(escalation!.cost_in_max_endpoint).toBeGreaterThan(ROSTER.ceiling_usd_per_m_input)
  })
})

describe('ModelPicker', () => {
  beforeEach(() => {
    resetModels()
    roster.value = ROSTER
    vi.stubGlobal('fetch', vi.fn(async () => jsonResponse(ROSTER)))
  })

  afterEach(() => {
    resetModels()
    vi.unstubAllGlobals()
  })

  function preset(tier: string) {
    return mount(ModelPicker, { props: { mode: 'preset' as const, tier } })
  }

  it('answers what a tier IS, which the console could not say before', () => {
    const text = preset('escalation').text()
    expect(text).toContain('google/gemini-3.8-flash')
    expect(text).toContain('Gemini 3.8 Flash')
  })

  it('shows BOTH prices, because the output half is the larger one', () => {
    /*
     * The budget model prices 4,253 completion tokens per call, so output
     * dominates every estimate. A row that showed only input would make the
     * meter look arbitrary.
     */
    const text = preset('escalation').text()
    expect(text).toContain('$0.75')
    expect(text).toContain('$3.75')
  })

  it('says what the cheap preset can actually bill, not only its headline', () => {
    const text = preset('cheap').text()
    expect(text).toContain('$0.30')
    expect(text).toContain('$0.54')
    expect(text).toContain('1.8')
  })

  it('does not shout about an inflation factor of one', () => {
    expect(preset('escalation').text()).not.toContain('Routed for speed')
  })

  it('renders a context window as a window rather than as a number', () => {
    expect(preset('cheap').text()).toContain('1.0M')
  })

  it('marks an unsupported capability disabled with the model named in the tooltip', () => {
    /*
     * D7's client half. `openai/gpt-4.1-nano` publishes no reasoning at all
     * (measured 2026-09-04), and the server reports `model-lacks-capability`
     * for a document that carries `reasoning_effort` anyway - so this is the
     * first of two gates, never the only one.
     */
    const wrapper = mount(ModelPicker, {
      props: { mode: 'pick' as const, modelValue: 'openai/gpt-4.1-nano' },
    })
    const off = wrapper.findAll('.capabilities li.off')
    expect(off.length).toBeGreaterThan(0)
    const reasoning = off.find((item) => item.text().includes('Reasoning'))
    expect(reasoning).toBeDefined()
    expect(reasoning!.attributes('aria-disabled')).toBe('true')
    expect(reasoning!.attributes('title')).toContain('openai/gpt-4.1-nano')
    expect(reasoning!.attributes('title')).toContain('reasoning_effort')
  })

  it('leaves a supported capability unmarked', () => {
    const wrapper = mount(ModelPicker, {
      props: { mode: 'pick' as const, modelValue: 'google/gemini-3.8-flash' },
    })
    const items = wrapper.findAll('.capabilities li')
    expect(items.length).toBe(4)
    expect(wrapper.findAll('.capabilities li.off')).toHaveLength(0)
  })

  it('answers `supports` per parameter, so one form asks once', () => {
    const wrapper = mount(ModelPicker, {
      props: { mode: 'pick' as const, modelValue: 'openai/gpt-4.1-nano' },
    })
    const api = wrapper.vm as unknown as {
      supports: (p: 'response_format' | 'reasoning_effort' | 'tools') => boolean
    }
    expect(api.supports('reasoning_effort')).toBe(false)
    expect(api.supports('response_format')).toBe(true)
    expect(api.supports('tools')).toBe(true)
  })

  it('offers every roster model and emits the id that was chosen', async () => {
    const wrapper = mount(ModelPicker, {
      props: { mode: 'pick' as const, modelValue: 'google/gemini-3.8-flash' },
    })
    const select = wrapper.get('select')
    expect(select.findAll('option')).toHaveLength(ROSTER.models.length)

    await select.setValue('qwen/qwen3.7-flash')
    expect(wrapper.emitted('update:modelValue')?.[0]).toEqual(['qwen/qwen3.7-flash'])
  })

  it('keeps a model the roster does not carry, marked, rather than rewriting the document', () => {
    /*
     * Dropping it from the select would silently rewrite the author's document
     * to the first legal option the moment they touched anything else. Showing
     * it leaves the document alone and lets the server's own `model-unknown`
     * say why - the same judgement `BillableForm` already makes for an
     * unregistered `agent_id`.
     */
    const wrapper = mount(ModelPicker, {
      props: { mode: 'pick' as const, modelValue: 'openai/o4-mini' },
    })
    expect(wrapper.text()).toContain('openai/o4-mini')
    expect(wrapper.text()).toContain('not in this build')
    expect(wrapper.get('select').attributes('aria-invalid')).toBe('true')
  })

  it('states the reason instead of rendering an empty control', () => {
    resetModels()
    rosterProblem.value = 'The model roster could not be loaded: the API answered 503 Error.'
    const wrapper = mount(ModelPicker, { props: { mode: 'preset' as const, tier: 'cheap' } })
    expect(wrapper.get('[role="alert"]').text()).toContain('503')
    expect(wrapper.find('select').exists()).toBe(false)
  })
})
