"""The frontend's trace fixture, generated by the REAL serializer and pinned.

`frontend/tests/fixtures/serializerFrames.ndjson` is the file the interpretation
layer is proved against (T2.1 of `docs/run-shell/DEFINITION-OF-DONE.md`): every
frame in it came out of `events/serializer.py`'s own ladder, through the real
`StreamSinkAdapter` and the real `FrameBuffer`, from CrewAI event objects. A
hand-written fixture would prove that the interpretation layer can read a file
somebody typed, which is not the claim anyone needs.

**Why a generator rather than a capture.** A capture off a live run answers for
the eight or nine event classes that run happened to raise. The ladder handles
about thirty, and the ones a trace rail most needs - a guardrail rejecting an
output and forcing a retry, an agent's reasoning line, a tool that failed, a
structured response that is a dict rather than prose - are exactly the ones a
happy path never produces. `frontend/tests/fixtures/syntheticRun.ndjson` is the
capture; this is the coverage, and the two are complementary rather than
alternatives.

**The roles are invented.** "Fact Checker", `verify_claims`, `ClaimAudit`: none
of them is the Idea Validator's, deliberately, because G2 forbids the
interpretation layer knowing any product's vocabulary and a fixture full of
`market_task` would let a role list masquerade as a general rule.

**Determinism.** Every event carries an explicit `timestamp` and the run id is
fixed, so `seq` and `ts` are functions of the script rather than of the clock.
`monotonic` is patched while the chunk events are fed, because the adapter
coalesces stream chunks inside a 250 ms window (decision 15) and three chunks
fed at machine speed would arrive as one frame on a fast machine and two on a
slow one - a fixture that regenerates differently on different hardware is not
a fixture.

**Line endings.** `core.autocrlf` is `true` here, so the working tree holds CRLF
and the object store LF. `committed()` normalises before comparing, which keeps
the comparison about content while staying exact about it - the same argument
`tests/builder/test_client_fixtures.py` makes at greater length.

Regenerate with:

    ./.venv/Scripts/python.exe -m tests.events.test_trace_fixture --write

No cost: no network, no model, no credential.
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone
import json
import pathlib
import sys
from types import SimpleNamespace
from typing import Any
import unittest
from unittest.mock import patch

from crewai.events import (
    AgentExecutionCompletedEvent,
    AgentExecutionStartedEvent,
    CrewKickoffCompletedEvent,
    CrewKickoffStartedEvent,
    LLMCallCompletedEvent,
    LLMCallStartedEvent,
    LLMGuardrailCompletedEvent,
    LLMGuardrailStartedEvent,
    LLMStreamChunkEvent,
    TaskCompletedEvent,
    TaskStartedEvent,
    ToolUsageErrorEvent,
    ToolUsageFinishedEvent,
    ToolUsageStartedEvent,
)
from crewai.events.types.flow_events import (
    FlowFinishedEvent,
    FlowStartedEvent,
    HumanFeedbackReceivedEvent,
    HumanFeedbackRequestedEvent,
    MethodExecutionFailedEvent,
    MethodExecutionFinishedEvent,
    MethodExecutionStartedEvent,
)
from crewai.events.types.logging_events import AgentLogsExecutionEvent

from brief_crew.events import FrameBuffer, NodeRegistry, StreamSinkAdapter

REPO = pathlib.Path(__file__).resolve().parents[2]
FIXTURE = REPO / "frontend" / "tests" / "fixtures" / "serializerFrames.ndjson"

RUN_ID = "trace-fixture"
FLOW = "ClaimAudit"
NODE = "verify"
ROLE = "Fact Checker"
TASK = "verify_claims"
MODEL = "openrouter/google/gemini-3.5-flash-lite:nitro"
CALL = "call-verify-1"

#: The clock every event is stamped from. Fixed, so `ts` is reproducible.
T0 = datetime(2026, 9, 5, 9, 0, 0, tzinfo=timezone.utc)

#: A completion with real newlines and markdown in it - the shape a Reporter
#: produces, and the one a trace row must flatten rather than render.
PROSE = (
    "## What I checked\n\n"
    "Three of the five claims resolve to a primary source.\n\n"
    "- The revenue figure is **supported** by the filing.\n"
    "- The headcount is not; the only citation is a press release.\n\n"
    "I am reporting what the sources support rather than what would make a "
    "tidier answer."
)

#: A structured reply. `_utterance_text` cannot find `content`/`text`/`output`
#: on a dict, so it falls through to `json.dumps` - and the newline inside
#: becomes the two characters backslash-n. That distinction is the whole
#: reason this case is in the fixture: a rail that strips `\n` the character
#: and not `\n` the escape shows one of these two and mangles the other.
STRUCTURED = {
    "summary": "Two claims failed.\nBoth are headcount claims.",
    "checked": 5,
}

#: The guardrail's own reply shape - the one `validator_guardrails` returns and
#: the smallest structured response the ladder ever sees.
GUARDRAIL_REPLY = {"valid": True, "feedback": None}


def _agent() -> Any:
    """Whatever the serializer reads off `event.agent`, and nothing else.

    A real `crewai.Agent` builds an LLM client, an httpx pool and an SSL trust
    store in its constructor - the cost `llm=None` on the two gates exists to
    avoid - and the fields anything downstream reads are `role` and `id`.

    `fingerprint` is `None` rather than absent because CrewAI's own event
    constructors reach for it (`events/types/task_events.py:106`) before this
    module ever sees the event, and an absent attribute raises there. `None` is
    what a task with no fingerprint carries.
    """

    return SimpleNamespace(role=ROLE, id="agent-fixture", fingerprint=None)


def _task() -> Any:
    return SimpleNamespace(name=TASK, id="task-fixture", fingerprint=None)


def events() -> list[Any]:
    """The run, as CrewAI would have raised it, one event per moment.

    Ordered as a real execution orders them: the flow starts, the method
    starts, the crew and the task and the agent open, the agent thinks, uses a
    tool, has a tool fail, calls a model three ways, is checked by two
    guardrails, closes, a human is asked and answers, and the method and the
    flow end - with a failure at the end because a fixture with no error frame
    cannot prove an error renders.
    """

    def ts(step: int) -> datetime:
        return T0 + timedelta(milliseconds=250 * step)

    identity: dict[str, Any] = {"agent_role": ROLE, "task_name": TASK}
    agent, task = _agent(), _task()

    return [
        FlowStartedEvent(
            flow_name=FLOW,
            inputs={"claim_set": "Q3 investor update"},
            timestamp=ts(0),
        ),
        MethodExecutionStartedEvent(
            flow_name=FLOW,
            method_name=NODE,
            state={},
            params={"claim_set": "Q3 investor update"},
            timestamp=ts(1),
        ),
        CrewKickoffStartedEvent(
            crew_name="Claim audit crew",
            inputs={"claim_set": "Q3 investor update"},
            timestamp=ts(2),
            **identity,
        ),
        TaskStartedEvent(context="Verify each claim against a primary source.", task=task, timestamp=ts(3), **identity),
        # `model_construct` for the two agent events, and only those two.
        # `AgentExecution*Event.agent` is annotated `BaseAgent`, so ordinary
        # construction runs pydantic's validator, which tries to build a real
        # `Agent` - an LLM client, an httpx pool and an SSL trust store, the
        # cost `llm=None` on the two gates exists to avoid, paid to write a
        # fixture. Nothing downstream reads more of the agent than `role`, so
        # skipping validation costs this fixture nothing and buys a test module
        # that constructs no model client at all.
        AgentExecutionStartedEvent.model_construct(
            agent=agent,
            task=task,
            tools=["claim_lookup"],
            task_prompt="Verify each claim against a primary source.",
            timestamp=ts(4),
            **identity,
        ),
        AgentLogsExecutionEvent(
            agent_role=ROLE,
            formatted_answer=SimpleNamespace(
                thought="The filing is the primary source; the press release is not."
            ),
            timestamp=ts(5),
            task_name=TASK,
        ),
        ToolUsageStartedEvent(
            tool_name="claim_lookup",
            tool_args={"query": "Q3 revenue filing"},
            timestamp=ts(6),
            run_attempts=1,
            **identity,
        ),
        ToolUsageFinishedEvent(
            tool_name="claim_lookup",
            tool_args={"query": "Q3 revenue filing"},
            started_at=ts(6),
            finished_at=ts(6) + timedelta(milliseconds=1400),
            output=json.dumps(
                {
                    "status": "ok",
                    "tool": "claim_lookup",
                    "query": "Q3 revenue filing",
                    "retrieved_at": "2026-09-05T09:00:02Z",
                    "result_count": 4,
                    "results": [
                        {"url": "https://example.com/filing", "title": "Q3 filing"},
                    ],
                    "notes": "One primary source, three secondary.",
                }
            ),
            from_cache=False,
            timestamp=ts(7),
            run_attempts=1,
            **identity,
        ),
        ToolUsageErrorEvent(
            tool_name="claim_lookup",
            tool_args={"query": "headcount 2026"},
            error="upstream returned 503 after two retries",
            timestamp=ts(8),
            run_attempts=2,
            **identity,
        ),
        # `messages` carried, because the real event carries them:
        # `crewai/llms/base_llm.py:594-596` passes `to_serializable(messages)`
        # on every call, and since 2026-09-06 the ladder fingerprints them into
        # `prompt_fingerprint` / `message_count` / `prompt_chars` (DoD row B5).
        # An event built here WITHOUT them makes this fixture - the committed
        # record of what the real ladder produces - quietly narrower than
        # production, and `tests/service/test_synthetic_identity_frames.py`
        # compares the no-cost double against exactly this record.
        LLMCallStartedEvent(
            call_id=CALL,
            model=MODEL,
            messages=[
                {"role": "system", "content": "You check claims against primary sources."},
                {"role": "user", "content": "Check the five claims in the brief."},
            ],
            timestamp=ts(9),
            **identity,
        ),
        LLMStreamChunkEvent(call_id=CALL, chunk="## What I checked\n\n", timestamp=ts(10), **identity),
        LLMStreamChunkEvent(call_id=CALL, chunk="Three of the five claims ", timestamp=ts(11), **identity),
        LLMStreamChunkEvent(call_id=CALL, chunk="resolve to a primary source.", timestamp=ts(12), **identity),
        LLMCallCompletedEvent(
            call_id=CALL,
            response=PROSE,
            call_type="llm_call",
            model=MODEL,
            usage={"prompt_tokens": 1840, "completion_tokens": 96},
            finish_reason="stop",
            response_id="resp-1",
            timestamp=ts(13),
            **identity,
        ),
        LLMGuardrailStartedEvent(
            guardrail="every claim cites a source",
            retry_count=0,
            timestamp=ts(14),
            **identity,
        ),
        LLMGuardrailCompletedEvent(
            success=False,
            result=None,
            retry_count=0,
            error="two claims cite no source",
            guardrail_name="every claim cites a source",
            timestamp=ts(15),
            **identity,
        ),
        LLMCallCompletedEvent(
            call_id="call-verify-2",
            response=STRUCTURED,
            call_type="llm_call",
            model=MODEL,
            usage={"prompt_tokens": 2100, "completion_tokens": 41},
            finish_reason="stop",
            response_id="resp-2",
            timestamp=ts(16),
            **identity,
        ),
        LLMGuardrailStartedEvent(
            guardrail="every claim cites a source",
            retry_count=1,
            timestamp=ts(17),
            **identity,
        ),
        LLMGuardrailCompletedEvent(
            success=True,
            result=None,
            retry_count=1,
            guardrail_name="every claim cites a source",
            timestamp=ts(18),
            **identity,
        ),
        LLMCallCompletedEvent(
            call_id="call-verify-3",
            response=GUARDRAIL_REPLY,
            call_type="llm_call",
            model=MODEL,
            usage={"prompt_tokens": 310, "completion_tokens": 8},
            finish_reason="stop",
            response_id="resp-3",
            timestamp=ts(19),
            **identity,
        ),
        AgentExecutionCompletedEvent.model_construct(
            agent=agent,
            task=task,
            output="Three of five claims are supported; two are not.",
            timestamp=ts(20),
            **identity,
        ),
        # Same reason as the agent pair above: `TaskCompletedEvent.output` is a
        # `TaskOutput` and `CrewKickoffCompletedEvent.output` a `CrewOutput`,
        # neither of which the ladder reads - the two branches emit
        # `{"stage": "after"}` and `{"stage": "after", "total_tokens": ...}`.
        TaskCompletedEvent.model_construct(
            output="Three of five claims are supported; two are not.",
            task=task,
            timestamp=ts(21),
            **identity,
        ),
        CrewKickoffCompletedEvent.model_construct(
            crew_name="Claim audit crew",
            output="Three of five claims are supported; two are not.",
            total_tokens=4295,
            timestamp=ts(22),
            **identity,
        ),
        HumanFeedbackRequestedEvent(
            flow_name=FLOW,
            method_name=NODE,
            output={"supported": 3, "unsupported": 2},
            message="Confirm the two unsupported claims before publication.",
            emit=None,
            request_id="gate-verify",
            timestamp=ts(23),
        ),
        HumanFeedbackReceivedEvent(
            flow_name=FLOW,
            method_name=NODE,
            feedback='{"decision": "approve"}',
            outcome=None,
            request_id="gate-verify",
            timestamp=ts(24),
        ),
        MethodExecutionFinishedEvent(
            flow_name=FLOW,
            method_name=NODE,
            state={},
            result={"supported": 3, "unsupported": 2},
            timestamp=ts(25),
        ),
        MethodExecutionFailedEvent(
            flow_name=FLOW,
            method_name=NODE,
            # A real exception, because the field is typed `Exception` - and
            # because `error_class_of` reads its type, which is the field a
            # client routes an error on.
            error=RuntimeError("no signing key configured"),
            timestamp=ts(26),
        ),
        FlowFinishedEvent(
            flow_name=FLOW,
            state={},
            result={"supported": 3, "unsupported": 2},
            timestamp=ts(27),
        ),
    ]


def build_frames() -> list[dict[str, Any]]:
    """Every event through the production capture path, as frame dicts.

    The adapter rather than the serializer alone, because the adapter is what
    allocates `seq`, coalesces the stream chunks and inserts `edge_traversal` -
    all three of which a client reads and none of which a bare `drafts()` call
    would produce.
    """

    buffer = FrameBuffer(capacity=512)
    adapter = StreamSinkAdapter(
        run_id=RUN_ID,
        buffer=buffer,
        registry=NodeRegistry(flow_method_nodes={NODE: NODE}),
    )
    # A monotonic clock that advances a whole second per read, so each stream
    # chunk is outside the 250 ms coalescing window and lands as its own frame.
    ticks = iter(float(step) for step in range(10_000))
    with patch("brief_crew.events.adapter.monotonic", lambda: next(ticks)):
        for event in events():
            adapter(None, event)
    return [frame.to_dict() for frame in buffer.replay()]


def render(frames: list[dict[str, Any]]) -> str:
    """The NDJSON the `/api/runs/{id}/logs` route writes, byte for byte.

    Same envelope and same separators as `service/app.py::download_logs`, so a
    frontend test can parse this file and a real export with one reader. A
    fixture in a shape the product never serves would be a second format to
    keep working.
    """

    return "".join(
        json.dumps({"type": "frame", "data": frame}, separators=(",", ":")) + "\n"
        for frame in frames
    )


def committed() -> str:
    """The fixture on disk, line endings normalised. See the module docstring."""

    return FIXTURE.read_text(encoding="utf-8").replace("\r\n", "\n")


def write() -> None:
    FIXTURE.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE.write_text(render(build_frames()), encoding="utf-8", newline="\n")


REGENERATE = "./.venv/Scripts/python.exe -m tests.events.test_trace_fixture --write"


class TraceFixtureTests(unittest.TestCase):
    def setUp(self) -> None:
        self.frames = build_frames()

    def test_the_committed_fixture_is_what_the_serializer_produces_today(self) -> None:
        self.assertEqual(
            render(self.frames),
            committed(),
            "frontend/tests/fixtures/serializerFrames.ndjson is stale. "
            f"Regenerate it with:\n    {REGENERATE}",
        )

    def test_it_is_deterministic_across_two_builds(self) -> None:
        """A fixture that regenerates differently is not a fixture."""

        self.assertEqual(render(self.frames), render(build_frames()))

    def test_every_kind_the_run_shell_reads_is_present(self) -> None:
        kinds = {frame["kind"] for frame in self.frames}
        self.assertEqual(
            kinds,
            {
                "run_state",
                "node_state",
                "agent",
                "reasoning",
                "tool",
                "llm",
                "token",
                "guardrail",
                "gate_open",
                "gate_closed",
            },
        )

    def test_the_three_stream_chunks_did_not_coalesce(self) -> None:
        chunks = [
            frame
            for frame in self.frames
            if frame["kind"] == "llm" and frame["details"].get("stage") == "chunk"
        ]
        self.assertEqual(len(chunks), 3)
        self.assertEqual(
            "".join(str(frame["details"]["chunk"]) for frame in chunks),
            "## What I checked\n\nThree of the five claims resolve to a primary source.",
        )

    def test_the_prose_utterance_keeps_its_newlines_and_markdown(self) -> None:
        text = self._utterance("call-verify-1")
        self.assertIn("\n", text)
        self.assertIn("**supported**", text)

    def test_the_structured_utterance_is_json_with_an_ESCAPED_newline(self) -> None:
        """The case a rail gets wrong in exactly one of two ways.

        `json.dumps` of a dict whose value contains a newline writes the two
        characters backslash and n. A row that strips control characters leaves
        that visible; a row that strips the escape mangles the prose case above.
        The fixture carries both so a spec cannot pass by handling one.
        """

        text = self._utterance("call-verify-2")
        self.assertIn("\\n", text)
        self.assertNotIn("\n", text)
        self.assertEqual(json.loads(text)["checked"], 5)

    def test_the_guardrail_reply_utterance_survives_a_null(self) -> None:
        self.assertEqual(json.loads(self._utterance("call-verify-3")), GUARDRAIL_REPLY)

    def test_both_guardrail_outcomes_are_there_with_their_retry_counts(self) -> None:
        outcomes = [
            (frame["details"].get("success"), frame["details"].get("retry_count"))
            for frame in self.frames
            if frame["kind"] == "guardrail" and frame["details"].get("stage") == "after"
        ]
        self.assertEqual(outcomes, [(False, 0), (True, 1)])

    def test_the_tool_envelope_reached_the_frame(self) -> None:
        after = self._one("tool", "after")
        self.assertEqual(after["details"]["result_count"], 4)
        self.assertEqual(after["details"]["query"], "Q3 revenue filing")
        self.assertEqual(after["details"]["tool_status"], "ok")

    def test_the_agent_frames_carry_the_invented_role_and_task(self) -> None:
        before = self._one("agent", "before", message_contains=ROLE)
        self.assertEqual(before["details"]["task"], TASK)
        self.assertEqual(before["details"]["agent_role"], ROLE)

    def test_no_idea_validator_vocabulary_leaked_into_the_fixture(self) -> None:
        """G2's rule, applied to the file the interpretation layer learns from.

        A fixture naming the Idea Validator's roles would let a spec written
        against it pass while the interpretation layer secretly knew one
        product's vocabulary.
        """

        blob = render(self.frames)
        for word in (
            "Scoper",
            "Market Analyst",
            "Sentiment",
            "Feasibility",
            "Synthesist",
            "Reporter",
            "market_task",
            "scope_idea",
            "research_market",
        ):
            self.assertNotIn(word, blob, f"{word!r} is the Idea Validator's")

    # -- helpers ---------------------------------------------------------
    def _utterance(self, call_id: str) -> str:
        for frame in self.frames:
            details = frame["details"]
            if details.get("stage") == "utterance" and details.get("call_id") == call_id:
                return str(details["text"])
        raise AssertionError(f"no utterance frame for {call_id}")

    def _one(
        self, kind: str, stage: str, *, message_contains: str | None = None
    ) -> dict[str, Any]:
        for frame in self.frames:
            if frame["kind"] != kind or frame["details"].get("stage") != stage:
                continue
            if message_contains and message_contains not in frame["message"]:
                continue
            return frame
        raise AssertionError(f"no {kind}/{stage} frame")


if __name__ == "__main__":  # pragma: no cover - regeneration entry point
    if "--write" in sys.argv:
        write()
        print(f"wrote {FIXTURE}")
    else:
        unittest.main()
