import { mkdirSync } from 'node:fs'
import path from 'node:path'
import { expect, test, type APIRequestContext, type Page } from '@playwright/test'

/**
 * The whole product at 1920x1080 — the owner's monitor.
 *
 * ## Why a viewport gets its own file
 *
 * Every other layout guard in this suite is written at 1440x900, because that
 * is the size the judge captures at. 1920x1080 is the size the product is
 * actually USED at, and the two are not the same question: the builder's fit is
 * floored at `MIN_LEGIBLE_ZOOM = 11/15` (`BuilderCanvas.vue:212`), so a graph
 * that does not fit inside that floor is CLIPPED rather than shrunk. How much
 * is clipped is a pure function of the pane, and the pane is a function of the
 * viewport. D-15-2 has been open for four judge rounds on exactly that
 * trade-off at 1440x900; whether it is a defect at 1080 is a measurement
 * nobody had taken.
 *
 * So this file measures rather than argues. Every assertion is a number read
 * out of a real browser — `boundingBox()`, `getComputedStyle`,
 * `elementFromPoint` — and never a pixel diff. There are no baselines here and
 * this file adds none: a screenshot-diff at a new viewport would be a picture
 * of today rather than a statement about legibility, and it would have to be
 * regenerated by every change that moved a node by a pixel.
 *
 * The screenshots it does write are for a HUMAN to read, into
 * `benchmarks/ours/1080/` — gitignored by the global `*.png` rule, like every
 * other capture set in this repository.
 *
 * ## Also: plan 12 criterion 10, at this viewport only
 *
 * The criterion asks for the six failure modes screenshotted at two viewports
 * in two themes and judged legible and recoverable. The owner has ruled it done
 * at 1920x1080 only. `e2e/failure-modes.spec.ts` proves the FRAMES and the
 * recovery for the same six modes through the API; what is added here is the
 * part only a browser can answer — that the cause is on the node without
 * hovering anything, and that a path forward is one click away — in both
 * themes.
 *
 * ## The backend
 *
 * The same one `failure-modes.spec.ts` documents, and for the same reason: the
 * five running modes are a value of `SYNTHETIC_FAILURE`, which is read by the
 * backend PROCESS and cannot be set from a browser.
 *
 *   SYNTHETIC=1 SYNTHETIC_BRANCH_DELAY_SECONDS=5 PORT=8094 \
 *   CREDENTIALS_MASTER_KEY=... BUILDER_ALLOW_GATELESS_GRAPHS=1 \
 *   RUN_RATE_LIMIT_MAX_RUNS=100 \
 *   SYNTHETIC_FAILURE="fm_bad_key:bad_key:1,fm_tool_timeout:tool_timeout:1,\
 *   fm_refusal:refusal:1,fm_malformed:malformed_output:1,fm_rate_limit:rate_limit:1" \
 *   ./.venv/Scripts/serve.exe
 *
 * Without it the criterion-10 tests SKIP and say so, rather than failing on an
 * environment gap that reads like a product defect.
 *
 * ## Cost
 *
 * Zero. `SYNTHETIC=1` swaps the crew factories and nothing else. The tests that
 * press Launch are tagged `@launch`; against a paid origin, exclude them.
 */

/** `benchmarks/ours/1080/`, relative to `frontend/`. Gitignored. */
const OUT = path.resolve(process.cwd(), '..', 'benchmarks', 'ours', '1080')

/** The owner's monitor. Every test in this file, both themes. */
test.use({ viewport: { width: 1920, height: 1080 } })

/**
 * The zoom floor, restated from `BuilderCanvas.vue:212` — `11 / 15`.
 *
 * The canvas refuses to fit below it, so a graph too big for the pane is
 * CLIPPED rather than shrunk. That is D-15-2's ruled trade, and this file
 * asserts the floor holds rather than re-litigating it.
 */
const MIN_LEGIBLE_ZOOM = 11 / 15

/**
 * What a 15px title renders at when the fit is on that floor: 11px.
 *
 * Every node kind uses `--fs-15` for `.builder-title` except two, and those two
 * are the finding this file records rather than fixes — see `MIN_ANY_TITLE_PX`.
 */
const MIN_CARD_TITLE_PX = 11

/**
 * And what the SMALLEST title of any kind renders at on the same floor: 9.53px.
 *
 * `13 * 11 / 15 = 9.533`. A router's title is `--fs-13` mono
 * (`builder.css:445`) and an attachment pill's is `--fs-12` (`:141`), while the
 * floor is computed from the 15px card title — `BuilderCanvas.vue:197-199` says
 * so in as many words. So the canvas's declared "never below 11px" is true for
 * seven kinds and false for the other two, at every viewport, and the brief's
 * 10px bar is missed by half a pixel on any graph holding a router.
 *
 * NOT FIXED HERE, deliberately, and the reasoning is the point:
 *
 *  - raising the floor to `11 / 13` = 0.846 would keep the promise and make the
 *    clipping strictly worse at every viewport, which is the side of D-15-2's
 *    trade four judge rounds have already rejected;
 *  - changing the router's type scale is a design decision about the node
 *    grammar (`is-kind-router` is mono at 13px on purpose) and would move
 *    committed pixel baselines, which is P-02's own subject;
 *  - and it is not a 1920x1080 defect at all. The floor is a constant and
 *    product-1 measured the same 0.733 fit at 1440x900, so `13 * 0.733` gives
 *    the same 9.53px there. That is arithmetic over two measured facts, not a
 *    third measurement — nothing in this session ran at 1440x900.
 *
 * The bound below therefore pins TODAY's arithmetic — a regression under it
 * fails — and the shortfall against 10px is carried in the report, not hidden.
 */
const MIN_ANY_TITLE_PX = 9.5

/**
 * Zero console errors, the rule `studio.spec.ts` sets for the whole suite.
 *
 * One exemption and it names its cause, exactly as `failure-modes.spec.ts`
 * declares it: the criterion-10 tests launch repeatedly and a Launch refused by
 * `RUN_RATE_LIMIT_MAX_RUNS` makes the browser log the 429 as a failed resource.
 * That console error is the limiter working. Narrow on purpose — any other
 * status, any Vue warning and any uncaught exception still fails.
 */
const ALLOWED_CONSOLE_ERROR = /429 \(Too Many Requests\)/

function watchConsole(page: Page): { unexpected: string[] } {
  const watch = { unexpected: [] as string[] }
  const record = (text: string) => {
    if (ALLOWED_CONSOLE_ERROR.test(text)) return
    watch.unexpected.push(text)
  }
  page.on('console', (message) => {
    if (message.type() === 'error') record(message.text())
  })
  page.on('pageerror', (error) => record(`uncaught: ${error.message}`))
  return watch
}

async function shot(page: Page, name: string): Promise<void> {
  mkdirSync(OUT, { recursive: true })
  await page.screenshot({ path: path.join(OUT, `${name}.png`), fullPage: false })
}

/* --- the measurements ----------------------------------------------------- */

interface Fit {
  /** The rendered zoom, read as `boundingRect.width / offsetWidth`. */
  zoom: number
  /** The SMALLEST rendered node title on the canvas, in device-independent px. */
  minTitlePx: number
  /** The id of the node carrying it, and its CSS font-size before the zoom. */
  minTitleId: string | null
  minTitleCssPx: number
  /** The smallest rendered title among cards using the primary `--fs-15`. */
  minCardTitlePx: number
  /**
   * Cards with SOME pixels outside the pane, and the worst excursion.
   *
   * Distinguished from `offPane` on the minimap's own definition
   * (`BuilderMinimap.vue:280-283`): a node clipped at the edge is one the author
   * can see and reach by panning a little, and counting it would make the
   * off-pane chip cry wolf on every graph wider than the pane.
   */
  clipped: { id: string; overflow: number }[]
  /** Cards with NO pixels on screen — the ones an author does not know exist. */
  offPane: string[]
  /** Cards whose TITLE is not wholly inside the pane. Legibility, not framing. */
  titlesCut: string[]
  nodes: number
}

/**
 * Every node's box against the pane's, and every title's RENDERED size.
 *
 * `offsetWidth` is unaffected by a CSS transform and the bounding rect is not,
 * so their ratio is the viewport's zoom — the reading `builder-layout.spec.ts`
 * already established, and for its reason: `getComputedStyle(...).transform` on
 * the Vue Flow viewport answers `none` here, and a confident zoom of 1 that is
 * really 0.66 is the exact wrong number this class of test exists to catch.
 *
 * A 0.5px tolerance on the pane edges, because a fit that lands a node exactly
 * on the boundary is not a clipped node and sub-pixel layout puts it either
 * side at random.
 */
async function measureFit(page: Page): Promise<Fit> {
  return page.evaluate(() => {
    const EDGE_TOLERANCE = 0.5
    const pane = document.querySelector('.builder-canvas')!.getBoundingClientRect()
    const cards = [...document.querySelectorAll('.vue-flow__node')] as HTMLElement[]
    const first = cards.find((card) => card.offsetWidth > 0)
    const zoom = first ? first.getBoundingClientRect().width / first.offsetWidth : 0

    let minTitlePx = Number.POSITIVE_INFINITY
    let minTitleId: string | null = null
    let minTitleCssPx = 0
    let minCardTitlePx = Number.POSITIVE_INFINITY
    const clipped: { id: string; overflow: number }[] = []
    const offPane: string[] = []
    const titlesCut: string[] = []

    for (const card of cards) {
      const id = card.getAttribute('data-id') ?? '?'
      const box = card.getBoundingClientRect()
      const overflow = Math.max(
        pane.left - box.left,
        box.right - pane.right,
        pane.top - box.top,
        box.bottom - pane.bottom,
      )
      if (overflow > EDGE_TOLERANCE) clipped.push({ id, overflow: Math.round(overflow) })
      // No overlap at all in either axis: the card has no pixels on screen.
      if (
        box.right < pane.left ||
        box.left > pane.right ||
        box.bottom < pane.top ||
        box.top > pane.bottom
      ) {
        offPane.push(id)
      }

      const title = card.querySelector('.builder-title') as HTMLElement | null
      if (!title) continue
      const titleBox = title.getBoundingClientRect()
      const titleOut = Math.max(
        pane.left - titleBox.left,
        titleBox.right - pane.right,
        pane.top - titleBox.top,
        titleBox.bottom - pane.bottom,
      )
      if (titleOut > EDGE_TOLERANCE) titlesCut.push(id)

      // The rendered size is the CSS size times the transform. Read that way
      // rather than off the title's own box, which a two-line clamp changes.
      const cssPx = parseFloat(getComputedStyle(title).fontSize)
      const px = cssPx * zoom
      if (px < minTitlePx) {
        minTitlePx = px
        minTitleId = id
        minTitleCssPx = cssPx
      }
      if (cssPx >= 15 && px < minCardTitlePx) minCardTitlePx = px
    }

    return {
      zoom: Number(zoom.toFixed(4)),
      minTitlePx: Number.isFinite(minTitlePx) ? Number(minTitlePx.toFixed(2)) : 0,
      minTitleId,
      minTitleCssPx,
      minCardTitlePx: Number.isFinite(minCardTitlePx) ? Number(minCardTitlePx.toFixed(2)) : 0,
      clipped,
      offPane,
      titlesCut,
      nodes: cards.length,
    }
  })
}

/**
 * The product's own claim about what is off-pane, against the measurement.
 *
 * `BuilderMinimap.offPane` counts cards with NO overlap at all, on the stated
 * grounds that a card clipped at the edge is one the author can see and reach.
 * So the chip is absent when nothing is wholly outside, and when something is
 * it must name the same number this file measured. Asserting the two together
 * is what stops either drifting alone — a silent chip over a hidden node is the
 * failure D-15-2 was opened for.
 */
async function offPaneChipAgrees(page: Page, fit: Fit): Promise<void> {
  const chip = page.locator('[data-testid="minimap-offpane"]')
  if (fit.offPane.length === 0) {
    expect(await chip.count(), 'the off-pane chip is lit with nothing off-pane').toBe(0)
    return
  }
  await expect(chip, `${fit.offPane.length} cards are off-pane and the chip is not lit`).toBeVisible()
  await expect(chip).toContainText(String(fit.offPane.length))
}

/**
 * Whether any part of `selector` is covered by something painted over it.
 *
 * `elementFromPoint` at the four corners and the centre: a control the author
 * cannot click is not a control, and a bounding box that is inside the pane
 * says nothing about what is drawn on top of it. Returns the tags/classes of
 * whatever actually answers, so a failure names the occluder rather than only
 * reporting a boolean.
 */
async function occludedBy(page: Page, selector: string): Promise<string[]> {
  return page.evaluate((target) => {
    const element = document.querySelector(target)
    if (!element) return ['<absent>']
    const box = element.getBoundingClientRect()
    if (box.width === 0 || box.height === 0) return ['<zero-sized>']
    const inset = 2
    const points: [number, number][] = [
      [box.left + inset, box.top + inset],
      [box.right - inset, box.top + inset],
      [box.left + inset, box.bottom - inset],
      [box.right - inset, box.bottom - inset],
      [box.left + box.width / 2, box.top + box.height / 2],
    ]
    const strangers = new Set<string>()
    for (const [x, y] of points) {
      const hit = document.elementFromPoint(x, y)
      if (!hit) {
        strangers.add('<offscreen>')
        continue
      }
      if (hit === element || element.contains(hit) || hit.contains(element)) continue
      strangers.add(`${hit.tagName.toLowerCase()}.${[...hit.classList].join('.')}`)
    }
    return [...strangers]
  }, selector)
}

/** A control whose own box escapes its scroll container is clipped. */
async function clippedControls(page: Page, container: string): Promise<string[]> {
  return page.evaluate((selector) => {
    const rail = document.querySelector(selector)
    if (!rail) return ['<absent>']
    const frame = rail.getBoundingClientRect()
    const out: string[] = []
    for (const control of rail.querySelectorAll('input, select, textarea, button')) {
      const box = control.getBoundingClientRect()
      // A control inside a collapsed <details> or a hidden tab has no box at
      // all; that is not clipping, it is not being rendered.
      if (box.width === 0 || box.height === 0) continue
      const over = Math.max(frame.left - box.left, box.right - frame.right)
      if (over > 1) {
        const id = control.getAttribute('id') ?? control.getAttribute('aria-label') ?? control.tagName
        out.push(`${id} overflows horizontally by ${Math.round(over)}px`)
      }
    }
    return out
  }, container)
}

/* --- getting somewhere ---------------------------------------------------- */

/**
 * Empty the signed-in author's library — UNPUBLISH FIRST, then delete.
 *
 * Decision 24: deleting a published document is refused with a 409, not
 * silently unpublished. `published-run.spec.ts`'s helper deletes only, which is
 * correct for the graphs it makes and leaves every published one behind — and
 * the leftovers land in the gallery, above the template grid. Measured: the
 * first clean run of this file reported `4 of 8` template cards above the fold
 * and a later one `0 of 8`, purely because thirteen published `Sequential
 * pipeline` rows from the launch tests were sitting on top of them. A gallery
 * capture taken over another test's rubbish is a picture of the harness.
 */
async function clearLibrary(request: APIRequestContext): Promise<void> {
  const listed = await request.get('/api/builder/workflows')
  if (!listed.ok()) return
  for (const entry of (await listed.json()) as { id: string }[]) {
    const removed = await request.delete(`/api/builder/workflows/${entry.id}`)
    if (removed.status() !== 409) continue
    await request.post(`/api/builder/workflows/${entry.id}/unpublish`)
    await request.delete(`/api/builder/workflows/${entry.id}`)
  }
}

async function openGallery(page: Page): Promise<void> {
  await page.goto('/#/build')
  await expect(page.locator('.template-card').first()).toBeVisible({ timeout: 30_000 })
}

async function openTemplate(page: Page, title: string, nodes: number): Promise<void> {
  await openGallery(page)
  await page.locator('.template-card', { hasText: title }).click()
  await expect(page.locator('.vue-flow__node')).toHaveCount(nodes, { timeout: 30_000 })
  await expect(page.locator('[data-testid="problems-checking"]')).toHaveCount(0, {
    timeout: 30_000,
  })
  // The settling ResizeObserver re-fits until the container stops moving; the
  // measurement has to be taken after it, not during it.
  await page.waitForTimeout(900)
}

/* ========================================================================== */
/* 1 · The gallery, and the flagship template                                 */
/* ========================================================================== */

test.describe('1 · the gallery and the sixteen-node template', () => {
  test('the gallery fits, and every validator node is whole and legible', async ({
    page,
    request,
  }) => {
    test.setTimeout(120_000)
    const watch = watchConsole(page)
    await clearLibrary(request)

    await openGallery(page)
    await page.waitForTimeout(400)
    await shot(page, '1a-gallery-dark')

    // The gallery's own row: at 1440x900 the third row of shapes sat 308px
    // below the fold (product-1, dimension 1). Measured here rather than
    // asserted, because "how many are above the fold" is the question and a
    // scroll container legitimately scrolls.
    const gallery = await page.evaluate(() => {
      const cards = [...document.querySelectorAll('.template-card')]
      const above = cards.filter((card) => card.getBoundingClientRect().bottom <= innerHeight)
      return { total: cards.length, aboveTheFold: above.length }
    })
    // eslint-disable-next-line no-console
    console.log(`1080 gallery: ${gallery.aboveTheFold} of ${gallery.total} cards above the fold`)

    await openTemplate(page, 'Idea validator', 16)
    const fit = await measureFit(page)
    // eslint-disable-next-line no-console
    console.log(
      `1080 validator on open: zoom ${fit.zoom} · smallest title ${fit.minTitlePx}px ` +
        `(${fit.minTitleCssPx}px CSS on ${fit.minTitleId}) · card titles ` +
        `${fit.minCardTitlePx}px · ${fit.clipped.length} of ${fit.nodes} clipped ` +
        `${JSON.stringify(fit.clipped)} · ${fit.offPane.length} wholly off-pane`,
    )
    await shot(page, '1b-validator-dark')

    /*
     * D-15-2's question at this viewport, in the three parts it actually has.
     *
     * 1. NOTHING IS INVISIBLE. Not one of the sixteen has zero pixels on
     *    screen — the failure the row was opened for, and the one the product's
     *    own off-pane chip counts.
     */
    expect(fit.offPane, `cards with no pixels on screen: ${fit.offPane.join(', ')}`).toEqual([])

    /*
     * 2. EVERY TITLE IS WHOLE. What the fit floor exists to protect is the
     *    readable part of a card, and a card clipped at its top or bottom edge
     *    has still said which node it is. This is the assertion that fails if
     *    the floor is ever removed.
     */
    expect(fit.titlesCut, `titles cut by the pane edge: ${fit.titlesCut.join(', ')}`).toEqual([])

    /*
     * 3. AND IT IS LEGIBLE. The floor holds, the primary card title lands on
     *    its declared 11px, and the smallest title of any kind is the router's
     *    9.53px — the shortfall `MIN_ANY_TITLE_PX` documents.
     */
    expect(fit.zoom, `the fit fell below the ${MIN_LEGIBLE_ZOOM.toFixed(4)} floor`).toBeGreaterThanOrEqual(
      MIN_LEGIBLE_ZOOM - 0.001,
    )
    expect(fit.minCardTitlePx).toBeGreaterThanOrEqual(MIN_CARD_TITLE_PX - 0.01)
    expect(
      fit.minTitlePx,
      `the smallest title is ${fit.minTitlePx}px on ${fit.minTitleId}`,
    ).toBeGreaterThanOrEqual(MIN_ANY_TITLE_PX)

    // The off-pane chip is the product's own claim about part 1, so the two are
    // asserted together and neither can drift alone.
    const strip = page.locator('[data-testid="minimap-offpane"]')
    expect(await strip.count(), 'the off-pane chip and the measurement disagree').toBe(
      fit.offPane.length ? 1 : 0,
    )

    expect(watch.unexpected).toEqual([])
  })

  test('light theme keeps the same fit', async ({ page, request }) => {
    test.setTimeout(120_000)
    const watch = watchConsole(page)
    await clearLibrary(request)
    await page.emulateMedia({ colorScheme: 'light' })

    await openGallery(page)
    await page.waitForTimeout(400)
    await shot(page, '7a-gallery-light')

    await openTemplate(page, 'Idea validator', 16)
    const fit = await measureFit(page)
    // eslint-disable-next-line no-console
    console.log(
      `1080 validator light: zoom ${fit.zoom} · title ${fit.minTitlePx}px · ` +
        `${fit.clipped.length} clipped · ${fit.offPane.length} off-pane`,
    )
    await shot(page, '7b-validator-light')

    // A theme cannot change a layout, and that is the assertion: the light
    // palette must land the same fit, not merely a pretty one.
    expect(fit.offPane).toEqual([])
    expect(fit.titlesCut).toEqual([])
    expect(fit.zoom).toBeGreaterThanOrEqual(MIN_LEGIBLE_ZOOM - 0.001)
    expect(fit.minTitlePx).toBeGreaterThanOrEqual(MIN_ANY_TITLE_PX)
    expect(watch.unexpected).toEqual([])
  })
})

/* ========================================================================== */
/* 2 · Versions and the delete strip, both docked                             */
/* ========================================================================== */

test.describe('2 · versions plus the delete strip', () => {
  test('says what it hides and lets a pan reach it, with both docked', async ({ page, request }) => {
    test.setTimeout(180_000)
    const watch = watchConsole(page)
    await clearLibrary(request)

    await openTemplate(page, 'Idea validator', 16)

    // Saved, so the version rail has something to list. Clicking the pane first
    // so the keystroke lands on the canvas rather than in a field.
    await page.locator('.builder-flow').click({ position: { x: 30, y: 30 } })
    await page.keyboard.press('Control+s')
    await expect(page.locator('[data-testid="save-chip"]')).toContainText(/saved/i, {
      timeout: 30_000,
    })

    await page.locator('[data-testid="document-menu-button"]').click()
    await page.locator('[data-testid="menu-versions"]').click()
    await expect(page.locator('[data-testid="version-browser"], .version-browser')).toBeVisible()

    await page.locator('[data-testid="document-menu-button"]').click()
    await page.locator('[data-testid="menu-delete"]').click()
    await expect(page.locator('[data-testid="delete-confirm"]')).toBeVisible()

    // The re-fit is the settling observer's and lands a frame or two after the
    // strip does, so the measurement waits for it to stop moving.
    await expect
      .poll(async () => (await measureFit(page)).zoom, { timeout: 12_000 })
      .toBeGreaterThan(0)
    await page.waitForTimeout(1_200)

    const fit = await measureFit(page)
    // eslint-disable-next-line no-console
    const pane = (await page.locator('.builder-canvas').boundingBox())!
    console.log(
      `1080 versions+delete: pane ${Math.round(pane.height)}px · zoom ${fit.zoom} · ` +
        `title ${fit.minTitlePx}px · ${fit.clipped.length} clipped · ` +
        `${fit.offPane.length} off-pane · ${fit.titlesCut.length} titles cut ` +
        `${JSON.stringify(fit.clipped)}`,
    )
    await shot(page, '2-versions-delete-dark')

    /*
     * MEASURED, AND IT IS D-15-2's TRADE AT ITS WORST POINT.
     *
     * Two strips take 188px off a 693px pane, leaving 505 for a graph that
     * needs 745 at the 11/15 floor — so five of the sixteen have no pixels on
     * screen at all, where with nothing docked the same five were clipped by
     * 26px. The brief's round-3 clause asks for "every node still whole"; at
     * 1920x1080 with both strips docked, the honest answer is that it is not,
     * and the report says so with this number rather than this file going green
     * over a softened assertion.
     *
     * NOT FIXED HERE. The three ways to fix it are all the ruled trade itself:
     * let the fit fall below the floor (rejected in rounds 2 and 3, because it
     * buys whole at the price of unreadable), make the docked strips overlay
     * the canvas (rejected by R15, whose whole subject is not covering the
     * graph you are editing), or cap the strips' height, which is a design
     * decision on a row a judge round owns. It is also not a 1920x1080 defect:
     * the strips take a fixed height and 1440x900 has 180px less to give them,
     * so it can only be worse there. That last sentence is ARITHMETIC over one
     * measurement, not a second measurement: nothing in this session opened
     * these two strips at 1440x900.
     *
     * What IS asserted is the pair of properties the product must deliver in
     * that state, and both hold: it SAYS what is hidden, and what it hides is
     * reachable.
     */
    await offPaneChipAgrees(page, fit)
    expect(fit.zoom).toBeGreaterThanOrEqual(MIN_LEGIBLE_ZOOM - 0.001)
    expect(
      fit.minTitlePx,
      `the smallest title is ${fit.minTitlePx}px on ${fit.minTitleId}`,
    ).toBeGreaterThanOrEqual(MIN_ANY_TITLE_PX)

    // REACHABLE: a pan brings a hidden card back. Space held, because
    // `pan-on-drag` is `[1, 2]` and a plain left drag draws a selection box and
    // pans nothing (`builder-layout.spec.ts` learned that the hard way).
    if (fit.offPane.length) {
      const hidden = fit.offPane[0]
      const frame = (await page.locator('.builder-canvas').boundingBox())!
      const x = frame.x + frame.width / 2
      const y = frame.y + frame.height / 2
      await page.keyboard.down('Space')
      await page.mouse.move(x, y)
      await page.mouse.down()
      await page.mouse.move(x, y + 260, { steps: 12 })
      await page.mouse.up()
      await page.keyboard.up('Space')
      await page.waitForTimeout(400)
      const panned = await measureFit(page)
      expect(
        panned.offPane,
        `a pan did not reach ${hidden}; still hidden: ${panned.offPane.join(', ')}`,
      ).not.toContain(hidden)
    }

    await page.locator('[data-testid="delete-cancel"]').click()
    expect(watch.unexpected).toEqual([])
  })
})

/* ========================================================================== */
/* 3 · The inspector, on an authored agent, with Expert on                    */
/* ========================================================================== */

test.describe('3 · the inspector with expert settings on', () => {
  /**
   * `Sequential pipeline` rather than the validator, because its agents are
   * AUTHORED — role, goal, backstory and task are the author's, so the form is
   * the long one. The validator's agents come from the crew library and render
   * a picker instead, which is the short form and the easy case.
   */
  async function inspectAgent(page: Page): Promise<void> {
    await openTemplate(page, 'Sequential pipeline', 7)
    await page.locator('.vue-flow__node[data-id="research"] .builder-node').click()
    await expect(page.locator('[data-testid="inspector-rail"]')).toBeVisible()
    const expert = page.locator('.expert-switch input')
    await expect(expert, 'the authored agent form offers no expert tier').toHaveCount(1)
    if (!(await expert.isChecked())) await expert.check()
    await page.waitForTimeout(400)
  }

  async function assertInspector(page: Page, name: string): Promise<void> {
    const rail = page.locator('[data-testid="inspector-rail"]')
    await expect(rail).toBeVisible()

    const clipped = await clippedControls(page, '[data-testid="inspector-rail"]')
    // eslint-disable-next-line no-console
    console.log(`1080 inspector ${name}: ${clipped.length} clipped controls`)
    expect(clipped, clipped.join('; ')).toEqual([])

    /*
     * The dock is visible, and not merely present.
     *
     * `[data-testid="builder-dock"]` is NOT it: that is the strip row above the
     * canvas (version browser, restore bar, import notice, delete confirm), and
     * it is legitimately zero-height with nothing docked — measured as `hidden`
     * here before this comment existed. The dock R15 is about is the problems
     * panel BELOW the canvas, which must stay on screen while the author edits;
     * an inspector that pushed it off the fold would be the modal the rail
     * exists not to be. The budget meter is asserted with it for the same
     * reason: those two are the surfaces that cost money to ignore.
     */
    for (const [label, selector] of [
      ['the problems dock', '.problems-panel'],
      ['the budget meter', '.budget-meter'],
    ] as const) {
      const strip = page.locator(selector)
      await expect(strip, `${label} is not on screen`).toBeVisible()
      const box = (await strip.boundingBox())!
      expect(box.height, `${label} has no height`).toBeGreaterThan(0)
      expect(box.y + box.height, `${label} ends at ${Math.round(box.y + box.height)}`).toBeLessThanOrEqual(1081)
      expect(box.y, `${label} starts above the viewport`).toBeGreaterThanOrEqual(0)
    }

    // And nothing is painted over the rail.
    const over = await occludedBy(page, '[data-testid="inspector-rail"]')
    expect(over, `the inspector is covered by ${over.join(', ')}`).toEqual([])

    await shot(page, name)
  }

  test('no control is clipped and the dock is visible — dark', async ({ page, request }) => {
    test.setTimeout(120_000)
    const watch = watchConsole(page)
    await clearLibrary(request)
    await inspectAgent(page)
    await assertInspector(page, '3-inspector-expert-dark')
    expect(watch.unexpected).toEqual([])
  })

  test('no control is clipped and the dock is visible — light', async ({ page, request }) => {
    test.setTimeout(120_000)
    const watch = watchConsole(page)
    await clearLibrary(request)
    await page.emulateMedia({ colorScheme: 'light' })
    await inspectAgent(page)
    await assertInspector(page, '7c-inspector-expert-light')
    expect(watch.unexpected).toEqual([])
  })
})

/* ========================================================================== */
/* 4 · The test panel, opened to its 60% ceiling                              */
/* ========================================================================== */

test.describe('4 · the test panel at 60% of the pane', () => {
  test('the canvas re-fits and nothing sits under the panel', async ({ page, request }) => {
    test.setTimeout(120_000)
    const watch = watchConsole(page)
    await clearLibrary(request)

    await openTemplate(page, 'Idea validator', 16)
    const before = await measureFit(page)

    await page.locator('[data-testid="test-panel-toggle"]').click()
    await expect(page.locator('[data-testid="test-panel-body"]')).toBeVisible()

    /*
     * Driven to the ceiling from the keyboard rather than by a pointer drag.
     *
     * `PANEL_MAX_FRACTION` is 0.6 of the graph pane and `setHeight` clamps to
     * it (`useFlowTest.ts:236,254`), so pressing Shift+Up past the top lands
     * exactly on 60% and stays there. A drag would have to guess a pixel
     * target, and the thing under test is the panel at its ceiling — not
     * whether a drag arrives at one.
     */
    const handle = page.locator('[data-testid="test-panel-handle"]')
    await handle.focus()
    for (let i = 0; i < 24; i += 1) await handle.press('Shift+ArrowUp')
    await page.waitForTimeout(900)

    const panel = (await page.locator('[data-testid="test-panel"]').boundingBox())!
    const pane = (await page.locator('.builder-canvas').boundingBox())!
    const fraction = panel.height / (panel.height + pane.height)
    const after = await measureFit(page)
    // eslint-disable-next-line no-console
    console.log(
      `1080 test panel: ${Math.round(panel.height)}px of ${Math.round(panel.height + pane.height)}` +
        ` = ${(fraction * 100).toFixed(1)}% · canvas ${Math.round(before.zoom * 1000) / 1000} -> ` +
        `${after.zoom} · ${after.clipped.length} clipped · ${after.offPane.length} off-pane`,
    )

    /*
     * It really is at `PANEL_MAX_FRACTION`, and until this session it could not
     * be: `useFlowTest.paneHeight` had no writer, so `maxHeight` resolved to
     * `PANEL_MIN_PX` and the handle moved the panel from 160px to 160px.
     * Measured before the fix, then after. `BuilderView.vue` carries the whole
     * account beside the observer that now feeds it.
     */
    expect(fraction, `the panel took ${(fraction * 100).toFixed(1)}% of the pane`).toBeGreaterThan(0.58)
    expect(fraction).toBeLessThanOrEqual(0.61)

    /*
     * THE POINT: the canvas re-fitted underneath the panel rather than keeping
     * the viewport it had when it was 469px tall.
     *
     * Measured as a RE-CENTRING, not as "nothing is clipped". A 292px pane
     * cannot hold a 745px graph at the 11/15 floor, and the product's ruled
     * answer to that is the off-pane chip rather than an illegible zoom — so
     * the assertion is that the graph's own centre tracks the pane's new
     * centre, which is what a fit does and what a stale viewport does not.
     */
    const centres = await page.evaluate(() => {
      const pane = document.querySelector('.builder-canvas')!.getBoundingClientRect()
      let top = Infinity
      let bottom = -Infinity
      for (const card of document.querySelectorAll('.vue-flow__node')) {
        const box = card.getBoundingClientRect()
        top = Math.min(top, box.top)
        bottom = Math.max(bottom, box.bottom)
      }
      return { graph: (top + bottom) / 2, pane: pane.top + pane.height / 2 }
    })
    expect(
      Math.abs(centres.graph - centres.pane),
      `the graph's centre is ${Math.round(centres.graph)} and the pane's is ${Math.round(centres.pane)}`,
    ).toBeLessThanOrEqual(4)
    expect(after.zoom).toBeGreaterThanOrEqual(MIN_LEGIBLE_ZOOM - 0.001)

    // And the product SAYS what the 60% stop costs, rather than quietly hiding
    // eight nodes. That is the whole difference between the round-2 state and
    // the round-3 one.
    await offPaneChipAgrees(page, after)

    /*
     * And NOTHING IS UNDER THE PANEL — asked of the browser rather than of a
     * bounding box, which is the distinction §14 defect 4 turned on. A card
     * whose box extends past the row is clipped by the row's own overflow and
     * is not "under" anything; a card actually PAINTED over the panel would
     * answer here. So the question is what `elementFromPoint` returns across
     * the panel's face, and the answer must never be a node.
     */
    const strangers = await page.evaluate(() => {
      const box = document.querySelector('[data-testid="test-panel"]')!.getBoundingClientRect()
      const found = new Set<string>()
      for (let col = 0; col <= 10; col += 1) {
        for (let row = 0; row <= 4; row += 1) {
          const x = box.left + 2 + ((box.width - 4) * col) / 10
          const y = box.top + 2 + ((box.height - 4) * row) / 4
          const hit = document.elementFromPoint(x, y)
          const node = hit?.closest('.vue-flow__node')
          if (node) found.add(node.getAttribute('data-id') ?? '?')
        }
      }
      return [...found]
    })
    expect(strangers, `nodes painted over the test panel: ${strangers.join(', ')}`).toEqual([])

    await shot(page, '4-test-panel-60-dark')
    expect(watch.unexpected).toEqual([])
  })
})

/* ========================================================================== */
/* 5 · Publish, Run it, and the console mid-run and completed                 */
/* ========================================================================== */

/** The one template with more than one phase, so a stage lane means something. */
const RUN_TEMPLATE = { title: 'Sequential pipeline', nodes: 7 }

async function publishAndRun(page: Page): Promise<void> {
  await openTemplate(page, RUN_TEMPLATE.title, RUN_TEMPLATE.nodes)
  await page.locator('.builder-flow').click({ position: { x: 30, y: 30 } })
  await page.keyboard.press('Control+s')
  await expect
    .poll(() => new URL(page.url()).hash, { timeout: 30_000 })
    .toMatch(/#\/build\/ug_[0-9a-f]{8}$/)

  await page.keyboard.press('Control+Shift+P')
  const dialog = page.locator('[aria-labelledby="publish-title"]')
  await expect(dialog).toBeVisible()
  await dialog.getByRole('button', { name: /^(Publish|Republish)$/ }).click()
  await dialog.getByRole('button', { name: /run it/i }).click()
  await expect(page.locator('.workflow-node')).toHaveCount(RUN_TEMPLATE.nodes, { timeout: 30_000 })

  // Review, for `studio.spec.ts`'s reason: `gatesMode` defaults to `auto`, and
  // against a backend without VALIDATOR_ALLOW_AUTO_GATES that is a 403.
  const review = page.getByRole('button', { name: 'Review', exact: true })
  if ((await review.getAttribute('aria-pressed')) !== 'true') await review.click()
  await page.locator('textarea#idea').fill('A weekly digest of what changed in our codebase.')
  await page.locator('.status-panel .control-actions button.button-primary').click()
}

/** The four metric cells, read in render order: elapsed, calls, tokens, cost. */
async function metrics(page: Page): Promise<Record<string, string>> {
  return page.evaluate(() => {
    const out: Record<string, string> = {}
    for (const cell of document.querySelectorAll('.metrics-grid div')) {
      const key = cell.querySelector('dt')?.textContent?.trim().toLowerCase() ?? '?'
      out[key] = cell.querySelector('dd')?.textContent?.trim() ?? ''
    }
    return out
  })
}

test.describe('5 · a published graph, mid-run and completed', () => {
  test.describe.configure({ mode: 'serial' })

  async function runAndCapture(page: Page, suffix: string): Promise<void> {
    await publishAndRun(page)

    // MID-RUN. The stage lane paints from the plan frames, which arrive at
    // kickoff, so it is up before the first node has finished.
    const lane = page.locator('.crew-progress')
    await expect(lane, 'a published graph got no stage lane').toBeVisible({ timeout: 90_000 })

    /*
     * The dialogue rail is the run's other narrative surface. It ships
     * COLLAPSED — `v-show="!collapsed"` on the list, and the head is the toggle
     * — so the rail has to be opened the way an operator opens it. Asserting it
     * visible without pressing it was a 90-second timeout on an element that
     * was in the DOM the whole time, which is exactly the reading a `toBeVisible`
     * on a `v-show` gives you.
     */
    const railToggle = page.locator('[data-testid="dialogue-toggle"]')
    if ((await railToggle.getAttribute('aria-expanded')) !== 'true') await railToggle.click()
    await expect(page.locator('[data-testid="dialogue-list"]')).toBeVisible({ timeout: 90_000 })

    // The handoff token walks the real edge path on an `edge_traversal` frame
    // and is removed inside four seconds, so it is waited FOR rather than
    // counted once.
    const token = page.locator('[data-testid="handoff-token"]').first()
    await expect(token, 'no handoff token walked an edge').toBeVisible({ timeout: 90_000 })

    await shot(page, `5a-run-midrun-${suffix}`)

    /*
     * The run console is a different canvas from the builder's — `.vue-flow`
     * inside `.graph-workspace`, with no `.builder-canvas` — so `measureFit`
     * does not apply and calling it here raised a null `getBoundingClientRect`.
     * What is measured instead is the question this viewport actually raises:
     * the console's three surfaces are all on screen at once, and none of them
     * is painted over the graph.
     */
    const console1080 = await page.evaluate(() => {
      const pane = document.querySelector('.vue-flow')!.getBoundingClientRect()
      const cards = [...document.querySelectorAll('.workflow-node')]
      const outside = cards.filter((card) => {
        const box = card.getBoundingClientRect()
        return (
          box.right < pane.left ||
          box.left > pane.right ||
          box.bottom < pane.top ||
          box.top > pane.bottom
        )
      }).length
      const onScreen = (selector: string) => {
        const box = document.querySelector(selector)?.getBoundingClientRect()
        return box ? box.height > 0 && box.top < innerHeight && box.bottom > 0 : false
      }
      return {
        nodes: cards.length,
        offPane: outside,
        lane: onScreen('.crew-progress'),
        rail: onScreen('.dialogue-rail'),
        status: onScreen('.status-panel'),
        // The right rail is taller than the viewport and SCROLLS, which is the
        // design (`.studio-main` is `minmax(0, 1fr)` with `min-height: 0` on
        // its children, §12's own fix). What must never happen is the PAGE
        // scrolling, which is the symptom of that fix being lost.
        pageScrolls:
          document.documentElement.scrollHeight > innerHeight + 1 ||
          document.documentElement.scrollWidth > innerWidth + 1,
      }
    })
    // eslint-disable-next-line no-console
    console.log(`1080 console mid-run (${suffix}): ${JSON.stringify(console1080)}`)
    expect(console1080.offPane, 'a console card has no pixels on screen').toBe(0)
    expect(console1080.lane, 'the stage lane is not on screen').toBe(true)
    expect(console1080.rail, 'the dialogue rail is not on screen').toBe(true)
    expect(console1080.status, 'the status panel is not on screen').toBe(true)
    expect(console1080.pageScrolls, 'the page itself scrolls; a rail should').toBe(false)

    // Answer whatever gates the template raises until it finishes.
    const badge = page.locator('.status-panel .status-badge')
    for (let i = 0; i < 60; i += 1) {
      if (/completed/i.test((await badge.textContent()) ?? '')) break
      const approve = page.locator('.gate-card').getByRole('button', { name: /^Approve/ })
      if (await approve.count()) await approve.first().click()
      await page.waitForTimeout(1_000)
    }
    await expect(badge).toHaveText(/completed/i, { timeout: 60_000 })

    const done = await metrics(page)
    await shot(page, `5b-run-completed-${suffix}`)

    /*
     * What the SERVER says the same run was, so the panel can be held against
     * it rather than against an opinion. This is the measurement that separates
     * "the console lost it" from "the run really was that short".
     */
    // The FULL id, off the element's own `title` — the visible text is the
    // first eight characters, and a prefix search needs a list endpoint whose
    // query shape this file got wrong once and logged a 422 for its trouble.
    const runId = (await page.locator('.status-panel .run-id').getAttribute('title')) ?? ''
    const server = await page.evaluate(async (id) => {
      if (!id) return null
      const frames = await fetch(`/api/runs/${id}/frames?limit=500`).then((r) => r.json())
      const rows = (frames.frames ?? []) as { data: { ts: string; kind: string } }[]
      const stamps = rows.map((f) => Date.parse(f.data.ts)).filter(Number.isFinite)
      return {
        frames: rows.length,
        frameSpanSeconds: stamps.length ? (Math.max(...stamps) - Math.min(...stamps)) / 1000 : null,
        tokenFrames: rows.filter((f) => f.data.kind === 'token').length,
      }
    }, runId)
    // eslint-disable-next-line no-console
    console.log(
      `1080 console completed (${suffix}): panel ${JSON.stringify(done)} · ` +
        `server ${JSON.stringify(server)}`,
    )

    /*
     * MEASURED, AND THE TWO HALVES HAVE DIFFERENT ANSWERS.
     *
     * The panel used to read `ELAPSED 00:00 · CALLS 0 · TOKENS 0 · $0.0000`,
     * which was P-08's sentence exactly. The server's own frames said why, and
     * they said two different things:
     *
     *   ELAPSED 00:00   HONEST, and still is. 46 frames spanning 0.45 s — a
     *                   synthetic builder run really is that short, and `mm:ss`
     *                   floors it. `feee876`'s frame-clock fallback is doing its
     *                   job and the run was under a second.
     *   TOKENS 0        NOT honest, and FIXED 2026-09-05. Three agents ran and
     *   CALLS 0         the run produced **zero frames of kind `token`**.
     *   COST $0.0000    `feee876` had fixed this for the synthetic VALIDATOR
     *                   runner (`service/runner.py`) and `builder_runner.py` is
     *                   a different runner, so a published graph somebody DREW
     *                   still got the panel P-08 described — on the one thing
     *                   `MAX_RUN_COST_USD` exists to bound.
     *
     * `_SyntheticCrew._bill` now emits the serializer's TOKEN frame after the
     * `utterance`, priced through `compute_cost_usd` off the tier's real model
     * constant rather than the tier NAME, which is why the cost was
     * unrecoverable even in principle before. So the assertion below is now the
     * strong one on both halves that were dishonest, and stays lenient on
     * `elapsed`, which is floored rather than wrong.
     *
     * `tokenFrames` is still measured and still asserted, because "the panel
     * shows a number" and "the server sent the frames it is computed from" are
     * different claims and this file has already been wrong about which it was
     * making.
     */
    expect(Object.keys(done).sort()).toEqual(['calls', 'cost', 'elapsed', 'tokens'])
    for (const [key, value] of Object.entries(done)) {
      expect(value, `the ${key} cell rendered nothing`).not.toBe('')
    }
    expect(server.tokenFrames, 'the run produced no frames of kind `token`').toBeGreaterThan(0)
    expect(done.tokens, 'TOKENS on a completed builder run').not.toBe('0')
    expect(done.calls, 'CALLS on a completed builder run').not.toBe('0')
    expect(done.cost, 'COST on a completed builder run').not.toBe('$0.0000')
  }

  test('the run console at 1920x1080 — dark', { tag: '@launch' }, async ({ page, request }) => {
    test.setTimeout(300_000)
    const watch = watchConsole(page)
    await clearLibrary(request)
    await runAndCapture(page, 'dark')
    expect(watch.unexpected).toEqual([])
  })

  test('the run console at 1920x1080 — light', { tag: '@launch' }, async ({ page, request }) => {
    test.setTimeout(300_000)
    const watch = watchConsole(page)
    await clearLibrary(request)
    await page.emulateMedia({ colorScheme: 'light' })
    await runAndCapture(page, 'light')
    expect(watch.unexpected).toEqual([])
  })
})

/* ========================================================================== */
/* 6 · Plan 12 criterion 10 at 1920x1080                                      */
/* ========================================================================== */

/** D8's five running modes, and the node each one is aimed at. */
const MODES = [
  { reason: 'bad_key', node: 'fm_bad_key' },
  { reason: 'tool_timeout', node: 'fm_tool_timeout' },
  { reason: 'refusal', node: 'fm_refusal' },
  { reason: 'malformed_output', node: 'fm_malformed' },
  { reason: 'rate_limit', node: 'fm_rate_limit' },
] as const

const AUTHORED_MODEL = 'google/gemini-3.8-flash'
const BODY_KEY = 'markdown_body'

/**
 * Laid out left to right, which `failure-modes.spec.ts` does NOT need to do.
 *
 * That file authors every node at `{x: 0, y: 0}` because it asserts over the
 * API and never looks at the canvas. Here the canvas is the whole subject, and
 * four cards at the origin stack on top of each other — the first capture taken
 * this session showed one card with another's error message under its header,
 * which is a picture of a fixture rather than of the product. Playwright's
 * `isVisible()` would not have caught it either: it asks about layout and
 * `visibility`, never about what is painted on top.
 */
function at(column: number) {
  return { x: column * 300, y: 0 }
}

function agentNode(id: string, source: string, column: number) {
  return {
    id,
    kind: 'agent',
    label: id,
    position: at(column),
    config: {
      role: `${id} specialist`,
      goal: `do the ${id} work`,
      backstory: 'years of it',
      task: {
        description: 'work from ${state.out__' + source + '}',
        expected_output: 'a paragraph',
      },
      llm: { model: AUTHORED_MODEL },
      tier: 'cheap',
      on_error: 'fail',
    },
  }
}

function edgeOf(id: string, source: string, target: string) {
  return { id, source, source_port: 'out', target, target_port: 'in' }
}

/**
 * `idea -> safe -> <failing> -> report`, gateless — the same document
 * `failure-modes.spec.ts` authors, and deliberately identical to it.
 *
 * Identical because `SYNTHETIC_FAILURE` names the NODE, so a document whose
 * failing node had a different id would need a different backend line, and two
 * files needing two backends is how one of them ends up silently skipping.
 */
function failingGraph(node: string) {
  return {
    schema: 'builder.flow/v1',
    name: `1080 failure mode ${node}`,
    version: 1,
    input_field: 'idea',
    nodes: [
      { id: 'idea', kind: 'input', label: 'idea', position: at(0), config: { field: 'idea' } },
      agentNode('safe', 'idea', 1),
      agentNode(node, 'safe', 2),
      {
        id: 'report',
        kind: 'output',
        label: 'report',
        position: at(3),
        config: { body_key: BODY_KEY, source: '${state.out__' + node + '}' },
      },
    ],
    edges: [edgeOf('e1', 'idea', 'safe'), edgeOf('e2', 'safe', node), edgeOf('e3', node, 'report')],
    joins: {},
  }
}

/** The cyclic document — a loop closed by a plain agent, which never runs. */
function cyclicGraph() {
  return {
    schema: 'builder.flow/v1',
    name: '1080 a loop closed by an agent',
    version: 1,
    input_field: 'idea',
    nodes: [
      { id: 'idea', kind: 'input', label: 'idea', position: at(0), config: { field: 'idea' } },
      agentNode('first', 'idea', 1),
      agentNode('second', 'first', 2),
      {
        id: 'report',
        kind: 'output',
        label: 'report',
        position: at(3),
        config: { body_key: BODY_KEY, source: '${state.out__second}' },
      },
    ],
    edges: [
      edgeOf('e1', 'idea', 'first'),
      edgeOf('e2', 'first', 'second'),
      edgeOf('e3', 'second', 'first'),
      edgeOf('e4', 'second', 'report'),
    ],
    joins: {},
  }
}

/** Whether the backend carries `SYNTHETIC_FAILURE` and the gateless flag. */
let knobPresent: boolean | null = null

async function requireKnob(request: APIRequestContext): Promise<void> {
  if (knobPresent === null) {
    const created = await request.post('/api/builder/workflows', {
      data: { document: failingGraph('fm_refusal') },
    })
    if (created.status() !== 201) knobPresent = false
    else {
      const id = ((await created.json()) as { document: { id: string } }).document.id
      const published = await request.post(`/api/builder/workflows/${id}/publish`)
      if (published.status() !== 200) knobPresent = false
      else {
        const launched = await request.post('/api/sessions/e2e-1080-probe/runs', {
          data: { workflow_id: id, inputs: { idea: 'probe' } },
        })
        if (launched.status() !== 202) knobPresent = false
        else {
          const runId = ((await launched.json()) as { run_id: string }).run_id
          const until = Date.now() + 60_000
          let status = 'unknown'
          while (Date.now() < until) {
            const snapshot = (await (await request.get(`/api/runs/${runId}`)).json()) as {
              status: string
            }
            status = snapshot.status
            if (['completed', 'failed', 'cancelled'].includes(status)) break
            await new Promise((resolve) => setTimeout(resolve, 200))
          }
          knobPresent = status === 'failed'
        }
      }
      // The probe PUBLISHED it, so a bare delete is the 409 decision 24 gives.
      await clearLibrary(request)
    }
  }
  test.skip(
    !knobPresent,
    'the backend was started without SYNTHETIC_FAILURE and BUILDER_ALLOW_GATELESS_GRAPHS. ' +
      'See this file\'s docstring.',
  )
}

/**
 * The two questions criterion 10 asks, asked of the browser rather than of me.
 *
 * LEGIBLE: the cause is on the node WITHOUT HOVER. So the assertion is that the
 * failing card carries `.is-error` and a `node-error-message` whose text is
 * non-empty and visible with the pointer parked in a corner — not that a
 * tooltip exists.
 *
 * RECOVERABLE: a path forward is ONE CLICK away. For the five running modes
 * that is `Re-run from here`, visible and enabled without opening anything. For
 * the cyclic mode it is the problems dock's row, which names the fix.
 */
interface Verdict {
  legible: boolean
  recoverable: boolean
  message: string
  /** WCAG contrast of the error sentence against what is painted behind it. */
  contrast: number
}

/**
 * WCAG 2.1 contrast between an element's text colour and its painted backdrop.
 *
 * "Legible" is a judgement until somebody puts a number on it, and this is the
 * number: 4.5:1 is AA for text under 18px, and the error sentence on a card is
 * 11px. The backdrop is found by walking ancestors until one has a
 * non-transparent `background-color`, because the card paints its own tint and
 * the line inside it does not — reading `getComputedStyle(line).background`
 * answers `rgba(0, 0, 0, 0)` and would score every theme as perfect.
 */
const CONTRAST_AA_SMALL = 4.5

async function contrastOf(page: Page, selector: string): Promise<number> {
  return page.evaluate((target) => {
    const element = document.querySelector(target)
    if (!element) return 0
    const parse = (value: string): [number, number, number, number] | null => {
      const parts = value.match(/[\d.]+/g)
      if (!parts || parts.length < 3) return null
      return [Number(parts[0]), Number(parts[1]), Number(parts[2]), parts[3] ? Number(parts[3]) : 1]
    }
    const luminance = ([r, g, b]: number[]) => {
      const channel = (raw: number) => {
        const c = raw / 255
        return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4
      }
      return 0.2126 * channel(r) + 0.7152 * channel(g) + 0.0722 * channel(b)
    }
    const fg = parse(getComputedStyle(element).color)
    if (!fg) return 0

    let backdrop: [number, number, number, number] = [255, 255, 255, 1]
    for (let node: Element | null = element; node; node = node.parentElement) {
      const found = parse(getComputedStyle(node).backgroundColor)
      if (found && found[3] > 0.9) {
        backdrop = found
        break
      }
    }
    // A semi-transparent foreground sits over the backdrop; composite it, or an
    // 80%-opacity grey scores as if it were solid.
    const composited = [0, 1, 2].map((i) => fg[3] * fg[i] + (1 - fg[3]) * backdrop[i])
    const light = Math.max(luminance(composited), luminance(backdrop))
    const dark = Math.min(luminance(composited), luminance(backdrop))
    return Number(((light + 0.05) / (dark + 0.05)).toFixed(2))
  }, selector)
}

async function judgeRunningMode(page: Page, node: string): Promise<Verdict> {
  const card = page.locator(`.vue-flow__node[data-id="${node}"]`)
  await expect(card.locator('.workflow-node.is-error')).toBeVisible({ timeout: 120_000 })

  // The pointer is parked away from the card first, so nothing below can be
  // true only because Playwright's last click left it hovering.
  await page.mouse.move(4, 4)
  await page.waitForTimeout(200)

  const message = card.locator('[data-testid="node-error-message"]')
  const text = (await message.innerText().catch(() => '')).trim()

  /*
   * `isVisible()` asks about layout and `visibility`; it does not ask what is
   * painted on top. So the sentence is also required to ANSWER at its own
   * centre — the check that would have caught the four-cards-at-the-origin
   * fixture that produced this file's first capture.
   */
  const onTop = await page.evaluate((node) => {
    const line = document.querySelector(
      `.vue-flow__node[data-id="${node}"] [data-testid="node-error-message"]`,
    )
    if (!line) return false
    const box = line.getBoundingClientRect()
    if (box.width === 0 || box.height === 0) return false
    const hit = document.elementFromPoint(box.left + box.width / 2, box.top + box.height / 2)
    return !!hit && (hit === line || line.contains(hit) || hit.contains(line))
  }, node)

  const contrast = await contrastOf(
    page,
    `.vue-flow__node[data-id="${node}"] [data-testid="node-error-message"]`,
  )
  const legible =
    (await message.isVisible()) && text.length > 0 && onTop && contrast >= CONTRAST_AA_SMALL
  const rerun = page.locator('[data-testid="rerun-from-here"]')
  const recoverable = (await rerun.isVisible()) && (await rerun.isEnabled())
  return { legible, recoverable, message: text, contrast }
}

test.describe('6 · plan 12 criterion 10 at 1920x1080', () => {
  test.describe.configure({ mode: 'serial' })

  for (const theme of ['dark', 'light'] as const) {
    for (const mode of MODES) {
      test(
        `@launch ${mode.reason} is legible and recoverable — ${theme}`,
        async ({ page, request }) => {
          test.setTimeout(240_000)
          await requireKnob(request)
          const watch = watchConsole(page)
          if (theme === 'light') await page.emulateMedia({ colorScheme: 'light' })

          const created = await request.post('/api/builder/workflows', {
            data: { document: failingGraph(mode.node) },
          })
          expect(created.status(), await created.text()).toBe(201)
          const id = ((await created.json()) as { document: { id: string } }).document.id

          // Published and launched through the UI, because what is under test
          // is the SCREEN. The API half is `failure-modes.spec.ts`'s.
          await page.goto(`/#/build/${id}`)
          await expect(page.locator('[data-testid="problems-checking"]')).toHaveCount(0, {
            timeout: 30_000,
          })
          await page.keyboard.press('Control+Shift+P')
          const dialog = page.locator('[aria-labelledby="publish-title"]')
          await expect(dialog).toBeVisible()
          await dialog.getByRole('button', { name: /^(Publish|Republish)$/ }).click()
          await dialog.getByRole('button', { name: /run it/i }).click()
          await expect(page.locator(`.vue-flow__node[data-id="${mode.node}"]`)).toBeVisible({
            timeout: 30_000,
          })

          const review = page.getByRole('button', { name: 'Review', exact: true })
          if ((await review.getAttribute('aria-pressed')) !== 'true') await review.click()
          await page.locator('textarea#idea').fill('A scheduling assistant for clinics.')
          await page.getByRole('button', { name: /^Launch/ }).click()

          const verdict = await judgeRunningMode(page, mode.node)
          // eslint-disable-next-line no-console
          console.log(
            `crit10 ${theme} ${mode.reason}: legible=${verdict.legible} ` +
              `recoverable=${verdict.recoverable} contrast=${verdict.contrast}:1 — ` +
              `"${verdict.message}"`,
          )
          await shot(page, `6-crit10-${mode.reason}-${theme}`)

          expect(
            verdict.legible,
            `${mode.reason}: the cause is not readable on the node (contrast ${verdict.contrast}:1)`,
          ).toBe(true)
          expect(verdict.recoverable, `${mode.reason}: no one-click path forward`).toBe(true)

          await clearLibrary(request)
          expect(watch.unexpected).toEqual([])
        },
      )
    }

    test(`the cyclic graph is refused legibly — ${theme}`, async ({ page, request }) => {
      test.setTimeout(180_000)
      const watch = watchConsole(page)
      if (theme === 'light') await page.emulateMedia({ colorScheme: 'light' })

      const created = await request.post('/api/builder/workflows', {
        data: { document: cyclicGraph() },
      })
      expect(created.status(), await created.text()).toBe(201)
      const id = ((await created.json()) as { document: { id: string } }).document.id

      await page.goto(`/#/build/${id}`)
      await expect(page.locator('[data-testid="problems-checking"]')).toHaveCount(0, {
        timeout: 30_000,
      })

      // LEGIBLE: the dock names the defect and the closing edge carries the
      // error tint, so the sentence has something to point at. The pointer is
      // parked, for the same reason as above.
      await page.mouse.move(4, 4)
      const row = page.locator('[data-testid="problem-back-edge-not-router"]')
      await expect(row).toBeVisible({ timeout: 30_000 })
      const sentence = (await row.innerText()).trim()
      const tinted = await page.locator('.builder-edge.has-error').count()
      const contrast = await contrastOf(page, '[data-testid="problem-back-edge-not-router"]')

      // RECOVERABLE: the row says what to do in one word an author can act on,
      // and publish is refused rather than silently failing later.
      const recoverable = /router/i.test(sentence)
      await expect(page.locator('[data-testid="problems-headline"]')).toContainText(/error/i)

      // eslint-disable-next-line no-console
      console.log(
        `crit10 ${theme} cyclic_graph: legible=${tinted === 1 && contrast >= CONTRAST_AA_SMALL} ` +
          `recoverable=${recoverable} contrast=${contrast}:1 — ` +
          `"${sentence.replace(/\s+/g, ' ')}"`,
      )
      await shot(page, `6-crit10-cyclic_graph-${theme}`)

      expect(tinted, 'the closing edge is not tinted').toBe(1)
      expect(contrast, `the dock row reads at ${contrast}:1`).toBeGreaterThanOrEqual(CONTRAST_AA_SMALL)
      expect(recoverable, 'the sentence does not say to use a router').toBe(true)

      await clearLibrary(request)
      expect(watch.unexpected).toEqual([])
    })
  }
})
